const toxicPhrases = [
    "pee-pee",
    "cumslut",
    "shitsplats",
    "d1cksucker",
    "macaco",
    "w@nkers",
    "ladboys",
    "dixiedike",
    "filipino",
    "b1tch35",
    "sex video",
    "porn video",
    "nude video",
    "porn",
    "nude",
    "sex",
    "bang",
    "sh1te",
    "sh1th3ad",
    "arse-fuckers",
    "rectum",
    "fuckarees",
    "tart",
    "getthefuckout",
    "hang",
    "popimp",
    "camel toe",
    "hitlerist",
    "cockmunch",
    "urethra play",
    "pimpsimp",
    "snowballing",
    "dumbass fucker",
    "butthole boy",
    "ejaculates",
    "macaca",
    "menage a trois",
    "veado",
    "rusty trombone",
    "yiffy",
    "heroin",
    "motherfukkings",
    "t1tties",
    "chupado",
    "pedophl",
    "merd",
    "kunilingus",
    "pornos",
    "m0fo",
    "footaction",
    "jimfish",
    "goddamn son-of-a-bitch",
    "negro",
    "assbag",
    "bitchfuck",
    "muthafuckings",
    "wh00r",
    "spic",
    "muffindiver",
    "tittys",
    "hookers",
    "cock knocker",
    "leather straight jacket",
    "assfuck",
    "gotohell",
    "boooobs",
    "snatch",
    "fastfuck",
    "fuckless",
    "bum-bandits",
    "foursome",
    "executioner",
    "pohm",
    "feltch",
    "booooooobs",
    "penisbreath",
    "pigfuckers",
    "fuckboy",
    "cock-face",
    "stupidfucks",
    "nigguhs",
    "assholz",
    "jizim",
    "slav",
    "ejaculated",
    "muschi",
    "motherlovebone",
    "geezer",
    "cooni3s",
    "wet dream",
    "jiga",
    "shiesterfuck",
    "perv",
    "sphincter",
    "brioco",
    "brunette action",
    "fags",
    "closet fuckhead",
    "wankings",
    "hymie",
    "fuckk",
    "pigfucker",
    "estupido",
    "sos",
    "corrupto",
    "b\uff01tch",
    "shitsful",
    "rachadinha",
    "anal hore",
    "muffdivers",
    "motherf@kka",
    "dumbbitch",
    "amcik",
    "autoerotic",
    "minority",
    "showtime",
    "hijack",
    "pussy",
    "sissy",
    "cock smoker",
    "pisser",
    "rabuda",
    "mothafucka",
    "rachadao",
    "fedido",
    "executed",
    "pleasure chest",
    "bombing",
    "die",
    "stripclub",
    "zigabo",
    "nojeira",
    "shit stain",
    "twat",
    "rosca",
    "brecha",
    "chota",
    "trannie",
    "meth",
    "devilworshipper",
    "shitterfucker",
    "fuku",
    "titfucks",
    "sh3male",
    "kyrpa*",
    "cocksuka",
    "homo",
    "sextoy",
    "fuckybrook",
    "defunto",
    "c00n",
    "horny",
    "bishes",
    "violence",
    "fuckybrooks",
    "mongrel",
    "pussyeater",
    "orafis",
    "gin",
    "goatse",
    "jizzim",
    "gun",
    "sexpot",
    "mother fucking",
    "nipplering",
    "gaiato",
    "dipshitty",
    "clusterfuck",
    "whor3",
    "snowback",
    "asspacker",
    "dick milker",
    "phone sex",
    "n1gg3r",
    "tribadism",
    "slopey",
    "spanking",
    "queef*",
    "pussys",
    "schmuck",
    "klootzak",
    "sodomise",
    "tw4t",
    "arseshit",
    "pish",
    "punkasses",
    "m0foes",
    "butt fucker",
    "queers",
    "homoerotic",
    "safado",
    "fuckoff",
    "motherfk",
    "mthrfcker",
    "dog fucking",
    "gayass",
    "mfukker",
    "shittydick",
    "b1tch3s",
    "pooperscooper",
    "assh0lez",
    "ejaculating",
    "git",
    "shagging",
    "basterd",
    "wang wrangler",
    "arabs",
    "peni5",
    "skanky",
    "siririca",
    "man chowder",
    "titlover",
    "fagit",
    "smackthemonkey",
    "balllicker",
    "arsehole",
    "looser",
    "smack",
    "stroking",
    "niggardly",
    "fuckdub",
    "dominatrix",
    "crack",
    "jizm",
    "shoot",
    "gipp",
    "mutha fucker",
    "queef",
    "scumfvck",
    "xrated",
    "voyeur",
    "lucifer",
    "fudgepackers",
    "foot fetish",
    "sadism",
    "vaj1na",
    "mofucker",
    "hells",
    "fore",
    "shittings",
    "blow",
    "witch",
    "coco",
    "higg@",
    "vibrater",
    "flatulence",
    "blumpkin boy",
    "fodao",
    "coon",
    "phuccer",
    "bagos",
    "duffer",
    "motherfecka",
    "knobs",
    "niiger;",
    "f@gg0t",
    "cuntfuckers",
    "backseat",
    "mafia",
    "disease",
    "mother effer",
    "cunteyed",
    "d0ggy style",
    "asshole",
    "shiesterfuckhead",
    "crotch",
    "kanake",
    "assassinate",
    "muffdivings",
    "freakfucks",
    "knob-head",
    "diseases",
    "chupada",
    "pissoffs",
    "anilingus",
    "jack-off",
    "fitt",
    "choke the chicken",
    "nutter",
    "sexymoma",
    "niggardliness",
    "mutha",
    "pimp",
    "shyt",
    "blow job",
    "doggo style",
    "jiggabo",
    "titt",
    "forni",
    "orgasms",
    "hard on",
    "assfkcer",
    "packerfudgehead",
    "peen",
    "foreskin",
    "cocaine",
    "pubic",
    "puuker",
    "kanker",
    "lezzian",
    "stupid",
    "nitwit",
    "queerasses",
    "n1gg3rs",
    "cocksuck",
    "pr1c",
    "camwhore",
    "anus plug",
    "whiskydick",
    "racial",
    "koon",
    "skum",
    "b17ch",
    "dildos",
    "frotting",
    "estupidez",
    "facefucker",
    "cuzudo",
    "cocksuckers",
    "slantfreak",
    "beaver cleaver",
    "slavedriver",
    "fcuk",
    "babeland",
    "snigger",
    "shortfuck",
    "troucha",
    "doggystyle",
    "fucs",
    "gaybor",
    "slanteyes",
    "spaghettinigger",
    "faggot son-of-a-bitch",
    "peehole",
    "b1tchs",
    "hustler",
    "peck",
    "masstrbate",
    "f@gging",
    "escroto",
    "b1otch",
    "fuckwad",
    "barenaked",
    "motherfuccers",
    "nsfw images",
    "motherfvck",
    "crabs",
    "skankybitch",
    "wetback",
    "mothter fuck",
    "nuggets",
    "gummer",
    "rosy palm",
    "muffdiver",
    "fuken",
    "pr1k",
    "horniest",
    "kurwa",
    "scum",
    "idiotice",
    "dick sucker",
    "bizzach",
    "tar-baby",
    "pus",
    "shittyfuck",
    "shitd1ck",
    "enculer",
    "gay fuck",
    "porchmonkey",
    "datnigga",
    "feck",
    "dumbass mofoes",
    "f@ggot",
    "bohunk",
    "goddamn mothafuckers",
    "fingering",
    "negros",
    "bastard",
    "ribbed",
    "shittastic",
    "crazy sob",
    "copulate",
    "uk",
    "chibumbo",
    "bates",
    "fer",
    "fodidafodido",
    "b!+ch",
    "sh!+",
    "knobead",
    "shitters",
    "slant",
    "thicklips",
    "bullshitted",
    "punheta",
    "nobjocky",
    "strap on",
    "cocklover",
    "sooty",
    "italiano",
    "jigger",
    "tw@t",
    "titbitnipply",
    "coot",
    "rearend",
    "cocksucker",
    "cockboy",
    "tard asses",
    "redlight",
    "cokmuncher",
    "scroat",
    "floo",
    "enema",
    "cyberfuck",
    "gayfuckist",
    "batty boy",
    "motherfukah",
    "kink",
    "sultry women",
    "fucking me",
    "wanker",
    "k!k3",
    "shat",
    "dego",
    "h0ar",
    "coloured",
    "primetime",
    "fanny",
    "dammit",
    "shitoutofluck",
    "crap",
    "phonesex",
    "perereca",
    "kaffir",
    "cum goon",
    "corrupta",
    "rugmuncher",
    "shitdip",
    "busty",
    "cnut",
    "bountybar",
    "cagado",
    "shited",
    "knob3nd",
    "masturba",
    "clitlickers",
    "chav",
    "masterbate",
    "higger",
    "mothafuckahs",
    "nadega",
    "sk@nks",
    "chin",
    "dick*",
    "penisfvcker",
    "clover clamps",
    "pule",
    "mothafuckings",
    "welfare",
    "panty",
    "coprolagnia",
    "spermherder",
    "cagona",
    "headlights",
    "crime",
    "kiss ass",
    "f0cker",
    "trouser snake",
    "arse-holes",
    "butchdyke",
    "skrib",
    "footjob",
    "jewish",
    "wab",
    "pilantra",
    "gaywad",
    "jiggy",
    "mof0s",
    "hebe",
    "fuck your",
    "fuck arse",
    "wuzzie",
    "motherfuckka",
    "injun",
    "kitchenshits",
    "ramela",
    "coprophilia",
    "cuntness",
    "bampot",
    "redneck",
    "sweetfucker",
    "futanari",
    "fatass",
    "canalha",
    "niccer",
    "penis-breath",
    "fuggings",
    "pissoff",
    "coksucka",
    "flange",
    "shit-ass",
    "cipa",
    "fuckhole",
    "sniggering",
    "fucking a",
    "mothercker",
    "jigaboo",
    "lezza",
    "phucks",
    "niggles",
    "cockblock",
    "ruski",
    "pissing",
    "wank off",
    "kotex",
    "hotpussy",
    "nigra",
    "scank",
    "stiffy",
    "snot",
    "ma5terb8",
    "dog shit",
    "shitty mofoes",
    "bloody",
    "gringo",
    "mijo",
    "gook",
    "jizzbags",
    "bazongas",
    "nignog",
    "asshats",
    "stump chewer",
    "motherfucks",
    "intheass",
    "cocksucking mothafuckers",
    "wormshits",
    "booty",
    "doo-doo",
    "god damn",
    "faggots",
    "one guy one jar",
    "beaver",
    "prick-head",
    "dipsticks",
    "shit-fucker",
    "furnica",
    "dildo",
    "ra8s",
    "mofo",
    "n1g3r",
    "cyberfucks",
    "vomit",
    "cumquat",
    "fuckas",
    "kitchenshit",
    "transvestite",
    "shitbox",
    "shitty",
    "cock munch",
    "condom",
    "furada",
    "hitler",
    "fukka",
    "shitmonkey",
    "slime",
    "niggor",
    "fvckker bunny",
    "spermbag",
    "lsd",
    "dumbshit",
    "azz",
    "spac",
    "butt-bang",
    "donkeyribber",
    "shhit",
    "shitsfuck",
    "lickme",
    "diks",
    "ass-holes",
    "erotism",
    "4skin",
    "cybersex",
    "ladyboy",
    "cock suck",
    "shrimping",
    "bwc",
    "mindfuck",
    "ball gravy",
    "blow a load",
    "assshit",
    "g-spot",
    "fuckload",
    "knobes",
    "n1ggahs",
    "oldfuck",
    "niga",
    "sleezeball",
    "niggur",
    "motherfckin",
    "cock-head",
    "shittiest",
    "mindfucked",
    "feiozo",
    "rat bastard",
    "snatch licker",
    "cumdumpster",
    "bogan",
    "ekrem*",
    "freakyfucker",
    "ejaculatings",
    "negroes",
    "dick face",
    "oldfuckers",
    "prostibulo",
    "vajina",
    "mocrea",
    "latin",
    "nobhead",
    "blowjobs",
    "hottotrot",
    "phuked",
    "penetration",
    "nigur;",
    "date rape",
    "splooge",
    "boiola",
    "stupidfuck",
    "mr hands",
    "assman",
    "greaseball",
    "mong",
    "fuckos",
    "pee",
    "twats",
    "arsefuck",
    "phukup",
    "dickbeaters",
    "piggyfuck",
    "usama",
    "coot coot",
    "iscroto",
    "bastid",
    "ball gag",
    "semen",
    "sonz of bitchez",
    "alabama hot pocket",
    "robber",
    "fag bag",
    "turnon",
    "cums",
    "shyty",
    "niger",
    "fuckers",
    "kike",
    "g0ddamned",
    "shitted",
    "tainted love",
    "dirty sanchez",
    "mutha fukker",
    "breasticles",
    "kurac",
    "va-j-j",
    "dick-face",
    "k..!ke",
    "fcvking",
    "mcfagget",
    "fuckster",
    "dild0",
    "buttman",
    "peru",
    "honger",
    "pakie",
    "wetspot",
    "flasher",
    "shytty",
    "pussies",
    "santorum",
    "motha fukkah",
    "manpaste",
    "cock droplets",
    "terrorist",
    "groid",
    "sexy-slim",
    "nigerian",
    "reverse cowgirl",
    "m0thafucked",
    "fotze",
    "mother fucka",
    "fourtwenty",
    "fucked up",
    "penile",
    "whitey",
    "nuckas",
    "packingfudge",
    "blumpkin",
    "cumjockey",
    "pocha",
    "spitter",
    "mother fucker",
    "weapon",
    "jackass",
    "fuck y0u",
    "coochie",
    "hoer",
    "china-virus",
    "fux0r",
    "hoes",
    "banging",
    "shyte",
    "moky",
    "f u c k e r",
    "mothafuckas",
    "fecker",
    "v14d0",
    "0rg@sm",
    "dick licker",
    "shiddick",
    "shittydicks",
    "esporro",
    "cumfests",
    "cuksuker",
    "lesbin",
    "fistfucked",
    "nigg3rs",
    "heshe",
    "dumbass",
    "penisfcker",
    "shit3",
    "asspirate",
    "mtherfuker",
    "@ssfcker",
    "suck",
    "double dicking",
    "shitloads",
    "piroco",
    "qweers",
    "merda",
    "motherfecker",
    "cyberfucked",
    "fuker",
    "mastabate",
    "killed",
    "asshore",
    "gonorrea",
    "packing fudge",
    "xota",
    "fistfuckers",
    "numbfuck",
    "p3n1shead",
    "dick-sneeze",
    "phukking",
    "cumjockeys",
    "asswhole",
    "niggahs",
    "jim crow",
    "feltching",
    "kill",
    "gosmenta",
    "weewee",
    "n1gr",
    "fuc",
    "crack-whore",
    "xerereca",
    "bich",
    "dickfucker",
    "nastyho",
    "felatio",
    "goddammed",
    "bigger",
    "pimpjuic",
    "sodomite",
    "headfuck",
    "cuntlickers",
    "c0ckhead",
    "analplug",
    "slutting",
    "lynch",
    "andskota",
    "5h1t",
    "nigre",
    "slutwear",
    "titfuckin",
    "cock rider",
    "wop",
    "gin jockey",
    "butt-fuck",
    "asslickers",
    "homos",
    "wetback*",
    "dumb fucker",
    "shitas",
    "lactate",
    "fuckaree",
    "monsterfuckers",
    "cockbite",
    "ass fuck",
    "cunt*",
    "cumz",
    "doggy style",
    "ku kluxer",
    "cocksucer",
    "kunt",
    "fuckarows",
    "fuckhea",
    "titwank",
    "spick",
    "gaygirl",
    "niggarded",
    "fukkings",
    "assbanger",
    "muthafuckah",
    "motherfuck",
    "muff diver",
    "meat curtains",
    "crapola",
    "shylock",
    "shitfreak",
    "fingerfucking",
    "butt hole",
    "nojento",
    "xibiu",
    "tarbaby",
    "dive",
    "ahole",
    "pemba",
    "fraud",
    "moles",
    "carpetmunchers",
    "pussy licker",
    "mfer",
    "felching",
    "cockskin",
    "c0cksucker",
    "mondronga",
    "faggo",
    "fudida",
    "p3nisfvcker",
    "fairy",
    "hindoo",
    "catshit",
    "ladyb0y",
    "fuk1n",
    "deggo",
    "slanty",
    "twa+",
    "tits",
    "dickfuck",
    "bater",
    "chochota",
    "shithouses",
    "pornography",
    "swastika",
    "phukked",
    "sonofbitch",
    "sexo",
    "dangit",
    "thundercunt",
    "cooties",
    "sweetfuckers",
    "shitt",
    "pubiclice",
    "dumasses",
    "double-dong",
    "shag",
    "69",
    "phaggot",
    "cockhead",
    "muffindivin",
    "ontherag",
    "hostage",
    "dilld0",
    "wrapping men",
    "rosy palm and her 5 sisters",
    "hoebag",
    "douchebag",
    "d!cks",
    "beastiality",
    "tight white",
    "dick fucker",
    "xexeca",
    "jewboy",
    "sodomy",
    "knobed",
    "nigger lover",
    "boom",
    "retardado",
    "dumb",
    "shitti",
    "mothafuckz",
    "willie",
    "mother fuck",
    "bugfuckers",
    "ballbag",
    "h0r",
    "c*nt",
    "fuckaround",
    "pierdol",
    "fed",
    "veada",
    "knobe",
    "cumshots",
    "fuucks",
    "niigr",
    "pen1s",
    "nudity",
    "jo cox",
    "bi curious",
    "shitless",
    "twathead",
    "b00bs",
    "screw",
    "ecstacy",
    "embarass",
    "embarassment",
    "embarassing",
    "dumbest",
    "dumber",
    "dummy",
    "seduce",
    "sexy",
    "sex",
    "fuck",
    "kill",
    "fugly",
    "thong",
    "cum",
    "vibr",
    "fucknuts",
    "boco",
    "jizzing",
    "loser",
    "tard",
    "dickwad",
    "dickheads",
    "genitals",
    "knockers",
    "viagra",
    "footlickers",
    "mothafcking",
    "tonguethrust",
    "machona",
    "cuntelope",
    "cuntsucker",
    "ass hole",
    "fukk",
    "homodumbshit",
    "suckme",
    "sapatao",
    "blackman",
    "assfk",
    "dogshit",
    "motha fuker",
    "willy",
    "knobd",
    "loadedgun",
    "phagot",
    "dominatrics",
    "fuckina",
    "cock sucker",
    "whoreface",
    "fucky",
    "orgasm",
    "ficken",
    "scag",
    "spooks",
    "lovegoo",
    "sharmuta",
    "bitchass",
    "cockmaster",
    "clit",
    "cunn",
    "sniper",
    "fucktons",
    "inthebuff",
    "mexican",
    "shittin",
    "ass bandit",
    "golliwog",
    "sh!t",
    "shit-bandit",
    "retardada",
    "salad tosser",
    "hiv",
    "raped",
    "cuntfucker",
    "xxx",
    "fingerfuck",
    "fuckadelic",
    "cow",
    "fuckwads",
    "Pu55y",
    "nigur",
    "nignigs",
    "paska*",
    "sk@nky",
    "fucck",
    "gangbang",
    "pancake face",
    "footfucks",
    "twinkie",
    "kyke",
    "cooter",
    "mutha fuker",
    "hotsex",
    "cleveland steamer",
    "dothead",
    "b1tchin",
    "fuckfests",
    "jackshit",
    "meat-sword",
    "twunter",
    "fucko",
    "blow your load",
    "motherfvcking",
    "faggoting",
    "dead",
    "dogie style",
    "alla",
    "asshole fucker",
    "dogstyle",
    "asspuppies",
    "blighter",
    "jigg",
    "jack-offs",
    "sh3mal3",
    "chinc",
    "guro",
    "criminal",
    "rabudona",
    "shitmonkeys",
    "vatican",
    "fxcking",
    "retardo",
    "fucc",
    "sh1t3",
    "fooker",
    "phukhead",
    "squaw",
    "fuckshithead",
    "sack",
    "duche",
    "jizzfucker",
    "spit",
    "phuq",
    "colored",
    "guiena",
    "muthafucker",
    "boshits",
    "fanyy",
    "bbc",
    "nlgger",
    "cuntass",
    "shitcan",
    "slanteye b1tch",
    "wakethefuckup",
    "gubba",
    "shitblimp",
    "fuckhead",
    "orgasum",
    "spank",
    "cockface",
    "fucks",
    "ass-hat",
    "scamfuck",
    "ky",
    "japs",
    "qahbeh",
    "pedophile",
    "wanks",
    "gay bitch",
    "dziwka",
    "ekto",
    "bicurious",
    "neggar",
    "furnicar",
    "hussy",
    "beaver lips",
    "sh1tdick",
    "nig nog",
    "fingerfuckers",
    "motherfukka",
    "va1jina",
    "athletesfoot",
    "doido",
    "nutsacks",
    "nigerians",
    "double pen",
    "jiggabooboo",
    "humping",
    "paky",
    "throating",
    "rabudo",
    "c0ck",
    "whiz",
    "orospu",
    "bung hole",
    "flamer",
    "gosma",
    "butt-fuckers",
    "fukkuh",
    "swinger",
    "baby batter",
    "lezbefriends",
    "h4ndjob",
    "jackasss",
    "nikkas",
    "piccaninny",
    "boll0ck",
    "s_h_i_s",
    "dog-fucker",
    "shitdikk",
    "husky",
    "mija",
    "phucking",
    "feio",
    "slutty",
    "faggotcock",
    "cemetery",
    "criminals",
    "badfuck",
    "bullet vibe",
    "sausage jockey",
    "tongue fucker",
    "knobz",
    "bullshittings",
    "cock tease",
    "hitlerism",
    "numbfucks",
    "your arse",
    "poonani",
    "fuckinas",
    "bicha",
    "slut hole",
    "dicklick",
    "birdshit",
    "wetb",
    "harder",
    "oh god",
    "kondum",
    "pimpjuice",
    "gatorbait",
    "f0ck",
    "vag1na",
    "fothermuckers",
    "fcukers",
    "boffing",
    "clamdiver",
    "numbnuts",
    "goddamnes",
    "gaytard",
    "sodomize",
    "fuckpigs",
    "arse-bandits",
    "spreadeagle",
    "fuckfreak",
    "taste my",
    "nipple",
    "phuck3r",
    "fugged",
    "fuck up",
    "xibumba",
    "fucknutt",
    "bugfucks",
    "fudgepacker",
    "l@dyb0y",
    "wally",
    "pooper",
    "fuckpig",
    "fux",
    "lugan",
    "lmao",
    "boazuda",
    "joint",
    "knob end",
    "dogs bollocks",
    "ginzo",
    "ass licking",
    "trashbitchez",
    "timbernigger",
    "spread legs",
    "vaginal",
    "phuqs",
    "rimjobs",
    "fecal",
    "fackuhs",
    "douche",
    "corna",
    "assfuckerz",
    "doochbag",
    "mindfucking",
    "rag head",
    "nepesaurio",
    "illegal",
    "a cock",
    "bolagato",
    "terror",
    "smegma",
    "*damn",
    "muthafeckers",
    "girls gone wild",
    "fingerpop",
    "pussylickers",
    "shitsdick",
    "prickteaser",
    "kills",
    "jailbait",
    "gosmento",
    "bitchslap",
    "octopussy",
    "throat yogurt",
    "itch",
    "dumbbitches",
    "dlcks",
    "dumb@ss",
    "limy",
    "fxcked",
    "b1tchy",
    "eejit",
    "bonk juice",
    "cock",
    "kaffre",
    "asslover",
    "penisfuccer",
    "pigshits",
    "erect",
    "mothafucker",
    "kiss my ass",
    "incest",
    "mastabater",
    "niggling",
    "damn",
    "sheister",
    "tittie5",
    "assranger",
    "taff",
    "whiskeydick",
    "honky",
    "tongue",
    "lovegun",
    "gay sex",
    "fuckingshitmotherfucker",
    "mothafcked",
    "d1cks",
    "bollick",
    "catholic",
    "bastardish",
    "fuckables",
    "buggery",
    "motherfvckeds",
    "0ral sex",
    "packing fudgehead",
    "fingerfuckings",
    "fvckwhi",
    "dookie",
    "meatrack",
    "gayboy",
    "cuntlicking",
    "buttermilk",
    "hotdamns",
    "fag queen",
    "fuckmonkeys",
    "suckmytit",
    "cumball",
    "mormon",
    "cuntlicks",
    "muthafuck",
    "b0llock",
    "fannyfuckers",
    "dumbass son-of-a-bitch",
    "footfuck",
    "crotchrot",
    "@ssfucker",
    "fiddlyfucker",
    "lies",
    "horn",
    "fuckbook",
    "triplex",
    "doggiestyle",
    "jungle bunny",
    "bugger",
    "bareback",
    "nicker",
    "fuckbooks",
    "jiss",
    "rimming",
    "p3nisfvckers",
    "tit",
    "cum",
    "cockcowboy",
    "cunt fart",
    "v14gra",
    "golden shower",
    "piranha",
    "tortur",
    "prostituta",
    "kumquat",
    "pi55",
    "lez",
    "twattish",
    "l@dyb0i",
    "sixsixsix",
    "cock snot",
    "shit-arse",
    "hork",
    "douche bag",
    "shitbreath",
    "lovemuscle",
    "big breasts",
    "fuckshitface",
    "phucup",
    "camslut",
    "stupid fucker",
    "futkretzn",
    "kitty puncher",
    "jerk-0ffs",
    "phukkeds",
    "whack off",
    "d1ckz",
    "cuzuda",
    "carpetmunching",
    "heeb",
    "cocksmoker",
    "bitchin",
    "bitcher",
    "muthafukkah",
    "black cock",
    "asswhore",
    "dipshite",
    "fuckton",
    "d4mn",
    "slantard",
    "spermacide",
    "taboo",
    "coon1es",
    "picaninny",
    "rola",
    "n3gro",
    "papeshit",
    "sh1s",
    "pixy",
    "pedo",
    "fag",
    "nojo",
    "anal hole",
    "batshit",
    "fuck face",
    "nawashi",
    "skankfuck",
    "stab",
    "suicide",
    "sadist",
    "blowjob",
    "divvy",
    "cunts",
    "pussy cat",
    "horse shit",
    "ohmygod",
    "motherfuccas",
    "f_u_c_k",
    "asian",
    "motherfucked",
    "cigs",
    "ar5e",
    "analplugs",
    "pecker",
    "violet wand",
    "polack",
    "fuckinright",
    "bi7ch",
    "vag",
    "cocknugget",
    "freakyfuckers",
    "shitte",
    "cuntfuck",
    "beaner",
    "pricks",
    "skankywhore",
    "asscracker",
    "fvcking",
    "cockjockey",
    "dick breath",
    "gonorreia",
    "motha fuckers",
    "holy fuck",
    "fok",
    "nigguhz",
    "shitassfuckface",
    "fuckingbitch",
    "bi",
    "cocaina",
    "assmuncher",
    "throater",
    "fingerfucks",
    "fuckasses",
    "gangbanged",
    "towelheads",
    "cuzao",
    "fcktard",
    "fuckar",
    "barmpot",
    "hoare",
    "c00nies",
    "cack",
    "palestinian",
    "bitch3s",
    "god-damn",
    "goddamit",
    "peener",
    "gaylord",
    "dogsh1t",
    "bastinado",
    "cockburger",
    "ho",
    "choad nectar",
    "bastards",
    "fedida",
    "polesmoker",
    "slimeball",
    "sons of bitches",
    "scheiss",
    "fck you",
    "cocksukka",
    "masturbating",
    "titlicker",
    "richfuck",
    "jebus",
    "molest",
    "dog style",
    "mindfucks",
    "pornprincess",
    "erection",
    "jigga",
    "cock-gobbler",
    "cumm",
    "fuckher",
    "punani",
    "diddlyshit",
    "cowshits",
    "fuckersucker",
    "shitblimps",
    "tuckahoe",
    "skumbag",
    "sperm",
    "fellate",
    "shitbug",
    "titties",
    "dumb ass",
    "splooge moose",
    "mijado",
    "tosser",
    "bbw",
    "dickforbrains",
    "gays",
    "mfukk",
    "n1ckker",
    "dogfuck",
    "dahmer",
    "stupidfucker",
    "fuckbuddy",
    "muthafuckers",
    "nojenta",
    "gyp",
    "bum",
    "mofos",
    "phucc",
    "doggin",
    "cag\u00e3o",
    "monsterfucker",
    "nazis",
    "cock sucking",
    "lipshitz",
    "necro",
    "whit",
    "handjobs",
    "lust",
    "b0llocks",
    "stringer",
    "mocreia",
    "uptheass",
    "wassack",
    "boner",
    "assholes",
    "whash",
    "hot chick",
    "fuck buttons",
    "bootycall",
    "ladra",
    "fudgepacking fucker",
    "cockrider",
    "assclown",
    "c0cksuccer",
    "motherfxcking",
    "ratshit",
    "dp action",
    "fker",
    "ball kicking",
    "fook",
    "cuntslut",
    "desire",
    "jackoffz",
    "pu55y",
    "kid diddler",
    "darktard",
    "grostulation",
    "animal fucker",
    "bum boy",
    "shitlicker",
    "scumfucker",
    "puddboy",
    "jizzsacks",
    "shitfires",
    "arse*",
    "cockless",
    "fuckmehard",
    "circlejerk",
    "n1ggazes",
    "suck my dick",
    "breastlover",
    "flipping the bird",
    "motherfckshit",
    "muffdive",
    "jackoffs",
    "jackasses",
    "d1ldo",
    "suka",
    "bint",
    "lesbain",
    "iscrota",
    "nickas",
    "hotdamn",
    "wassock",
    "cock suckers",
    "spunk",
    "cocklovers",
    "dickjockies",
    "buttwipe",
    "assfukker",
    "mfing",
    "butchbabes",
    "ladboyz",
    "beyoch",
    "backdoorman",
    "rabo",
    "dripdick",
    "kyrpa",
    "smeghead",
    "kunts",
    "mfckers",
    "male squirting",
    "assnigger",
    "fuckface",
    "sx",
    "queerz",
    "dixiedyke",
    "honk",
    "shitfuckers",
    "tramp",
    "bong",
    "moslem",
    "clitfuck",
    "orgasims",
    "dummy",
    "deepthroat",
    "phukings",
    "fagot",
    "tub girl",
    "shitfull",
    "cadela",
    "fucking shit",
    "fugger",
    "sht",
    "loverocket",
    "jihad",
    "mgger",
    "harlot",
    "k1ke",
    "gowl",
    "pack my fudge",
    "assshole",
    "porno",
    "machorra",
    "jigro",
    "tittyfuck",
    "barfface",
    "chinamen",
    "mothaf@cked",
    "asswipe",
    "bitchy ass",
    "motherfuckins",
    "dicklicker",
    "testicles",
    "muthafuker",
    "assfuckers",
    "tampon",
    "pommy",
    "veadao",
    "grelo",
    "nigga lover",
    "go fuck yourself",
    "blind",
    "narcotic",
    "mudderfuk",
    "ekrem",
    "d!ld0",
    "dick nibbler",
    "execute",
    "faig",
    "piss",
    "shitfucks",
    "goyim",
    "fcker",
    "lubejob",
    "fuckin",
    "moneyshot",
    "dlck",
    "gonzagas",
    "d1ckhead",
    "lardass",
    "pigfucking",
    "deapthroat",
    "breastman",
    "fuck off",
    "boang",
    "fuckknob",
    "cocksuckings",
    "cunnilingus",
    "bumhole",
    "cocksuccers",
    "pedobears",
    "prince albert piercing",
    "skankee",
    "cu",
    "escort",
    "window licker",
    "clamdigger",
    "fuckfingers",
    "s&m",
    "dumb bastard",
    "shitedick",
    "muthafukah",
    "gippo",
    "cunnie",
    "nobjokey",
    "gayfuck",
    "shitter",
    "abortion",
    "puzzies",
    "clitface",
    "dirsa",
    "dogsh1ts",
    "cunntt",
    "nymphomaniac",
    "ph@ggots",
    "b1otchs",
    "wet back",
    "cocklicker",
    "kummer",
    "cockh3ad",
    "dickman",
    "brotherfucker",
    "slopy",
    "muthafuckkers",
    "assfvck3r",
    "dry hump",
    "jerkoff jerking off",
    "pussie",
    "ass muncher",
    "creamy",
    "niggarding",
    "fudgepackershitter",
    "buttface",
    "fukwhit",
    "footlicker",
    "m45terbate",
    "fuckwit",
    "sexhound",
    "licker",
    "blacks",
    "jizz eater",
    "m0ng0l0id",
    "baitola",
    "pussylicking",
    "cyberfuckers",
    "bunduda",
    "richfucks",
    "nigg@s",
    "fuckme",
    "idiot",
    "shav",
    "b1tches",
    "pud",
    "pussylicker",
    "japa",
    "faggy",
    "bj",
    "c0cksuckers",
    "full of shit",
    "turdhead",
    "fiddlyfucking",
    "pillock",
    "moleque",
    "muthafuckahs",
    "areola",
    "whacker",
    "jerkoffs",
    "meleca",
    "horney",
    "doggy_style",
    "gay fucker",
    "pussypounder",
    "gaymuthafuckinwhore",
    "fckahz",
    "mofuck",
    "bigbutt",
    "jijjiboo",
    "phuker",
    "mothafuck",
    "williewanker",
    "threesome",
    "ot-rio",
    "skanck",
    "mofoes",
    "undressing",
    "m0therfucking",
    "nigah",
    "nut butter",
    "fuk",
    "xtc",
    "clusterfucking",
    "faggot mothafuckers",
    "otario",
    "two girls one cup",
    "fisting",
    "crackpipe",
    "nickk3r",
    "masturbat",
    "fire",
    "trolha",
    "sh1tz",
    "israel",
    "pica",
    "knobeds",
    "refugee",
    "masterbates",
    "crappy",
    "knickers",
    "cunty",
    "trocha",
    "kissass",
    "papeshits",
    "puss",
    "firing",
    "sheeney",
    "ash0le",
    "hung",
    "vjayjay",
    "fuckloads",
    "fedor",
    "@$$",
    "shi+y",
    "mothafuckeds",
    "jesus",
    "dickz",
    "corruption",
    "mothafuccer",
    "killing",
    "cooly",
    "assassin",
    "crash",
    "fukah",
    "bean queen",
    "zabourah",
    "vullva",
    "c0k",
    "wh0re",
    "fuckheaded",
    "sadom",
    "allah",
    "leather restraint",
    "orgasim",
    "dogfucker",
    "missionary position",
    "fudendo",
    "brothel",
    "bi+ch",
    "fuckups",
    "recktum",
    "k1k3",
    "pegging",
    "hoor",
    "mockie",
    "fuckdubs",
    "arsefucker",
    "roach",
    "knobgobbler",
    "fag asses",
    "mufdivin",
    "n1gguh",
    "butt plug",
    "abbie",
    "punanny",
    "cocknob",
    "kuntz",
    "d!ck",
    "nicka",
    "fornica",
    "b1tch1ng",
    "eatpussy",
    "fuckfinger",
    "fukked",
    "rabao",
    "flikker",
    "redskin",
    "ball sack",
    "wn",
    "lapdance",
    "wankers",
    "pindick",
    "fiddlyfucks",
    "figging",
    "3jakulating",
    "chraa",
    "unfucked",
    "nook",
    "shitdicks",
    "slideitin",
    "feia",
    "dickless",
    "hijacking",
    "dyefly",
    "jerk off",
    "knobbing",
    "fingerbanged",
    "nookie",
    "checheca",
    "pustula",
    "phuk",
    "sexkitten",
    "mother fuckers",
    "gayz",
    "shitefuck",
    "devil",
    "bullshits",
    "vietcong",
    "baby juice",
    "testicle",
    "fucx",
    "pansy",
    "cockheads",
    "hymen",
    "piss shit",
    "masterblaster",
    "bollok",
    "white power",
    "cohee",
    "carpetmuncher",
    "goatcx",
    "penises",
    "loose woman",
    "dickweasel",
    "t1tt1e5",
    "sexually",
    "abeed",
    "f@gshit",
    "trouxa",
    "shibari",
    "pu55i",
    "r3tard",
    "a_s_s",
    "cuntless",
    "nittit",
    "groper",
    "mother fuker",
    "whoar",
    "*shit*",
    "dick head",
    "fagfucker",
    "pillu*",
    "pedoz",
    "bast",
    "gay wad",
    "shithead",
    "dilld0s",
    "barelylegal",
    "fuckfest",
    "shita",
    "bollockchops",
    "p0rn",
    "cocksucking",
    "gayest",
    "niggerhead",
    "cunt",
    "titfuckers",
    "man seed",
    "unfuck",
    "swallow",
    "breast",
    "pusses",
    "unfuckable",
    "goo girl",
    "fvcka",
    "jiggabu",
    "catholics",
    "fcuked",
    "penis",
    "shiteaters",
    "b to the inch",
    "rentafuck",
    "nastt",
    "fingerbang",
    "fukwit",
    "motha fucka",
    "m0therfvcker",
    "r3t@rd",
    "vagabundo",
    "womens",
    "asskisser",
    "puto",
    "fuckingbitchs",
    "weiner",
    "goregasm",
    "skinflute",
    "ladrao",
    "shitfuckmotherfucker",
    "fcks",
    "fistfucks",
    "analsex",
    "m@asterbated",
    "lameass",
    "screwyou",
    "jiggerboos",
    "fagots",
    "buttfuckers",
    "footfucker",
    "whores",
    "niigr;",
    "caga",
    "mfk",
    "dickbrains",
    "muffdiving",
    "asshat",
    "pussyfucker",
    "fister",
    "lolita",
    "cobb knobbler",
    "cox",
    "shitfucker",
    "retardotron",
    "4r5es",
    "mother fuck you",
    "poontsee",
    "ponyplay",
    "masterbaiter",
    "prick",
    "sucker",
    "lovejuice",
    "gobshite",
    "shittasticfuck",
    "titty",
    "spigotty",
    "pooping",
    "peia",
    "clusterfucked",
    "cuntits",
    "klan",
    "suck my d",
    "muffdives",
    "fetish",
    "godamnit",
    "zoophilia",
    "xx",
    "mothafuker",
    "suckoff",
    "jesuschrist",
    "poon",
    "fuck",
    "boiolas",
    "jizz licker",
    "ass-fucker",
    "sixtynine",
    "2g1c",
    "prostitute",
    "faigs",
    "nastyslut",
    "wophead",
    "mcfucking",
    "pole licker",
    "cocksniffer",
    "knob gobbler",
    "charva",
    "mosshead",
    "asskissers",
    "packingfudgefucker",
    "chesticles",
    "motha fucker",
    "m0thafucking",
    "skankbitch",
    "g@y b1tch",
    "fuckbutter",
    "horses asses",
    "destroy",
    "dickbag",
    "fucksticks",
    "mothafukker",
    "wank*",
    "gangsta",
    "whitetrash",
    "tacohead",
    "boonga",
    "arsebandit",
    "peenus",
    "dirty",
    "beat my meat",
    "ape shite",
    "ass kisser",
    "assfuccer",
    "asholes",
    "sh1ter",
    "shit",
    "fondle",
    "peeenusss",
    "munt",
    "teets",
    "finger",
    "shitfacefucker",
    "shitfvck",
    "tarada",
    "gyppo",
    "v1gra",
    "mad",
    "knobend",
    "arab",
    "cyberfukks",
    "cornudo",
    "niggahz",
    "cocksuk",
    "scat",
    "mothafucked",
    "fuckaz",
    "cock head",
    "ass-jabber",
    "asslick",
    "shit licker",
    "sh1tfuck",
    "hard core",
    "tunneloflove",
    "beatyourmeat",
    "breastjob",
    "geebag",
    "geez",
    "cockwaffle",
    "testuda",
    "caca",
    "tongethruster",
    "god-damned",
    "baptist",
    "noonan",
    "skurwysyn",
    "fuckwitt",
    "mothafuckah",
    "cumming",
    "pissers",
    "mfs",
    "mothafucking",
    "shitheadfucker",
    "spicshit",
    "screwing",
    "shaggin",
    "packsomefudgefucker",
    "bitched",
    "slapper",
    "breasts",
    "darkass",
    "suckdick",
    "arse-bandit",
    "booby",
    "estupida",
    "asssucker",
    "dipshit",
    "buttstain",
    "big knockers",
    "ejackulate",
    "bollocktician",
    "honkers",
    "pawn",
    "what the fuck",
    "bunda",
    "motherfuckeds",
    "fvcker",
    "kigger",
    "rachada",
    "pig fucker",
    "fuckery",
    "sexed",
    "assh0le",
    "bazooms",
    "shits",
    "fuckum",
    "tongue fucking",
    "prostituto",
    "nastybitch",
    "cawks",
    "mother-fucker",
    "masturbat*",
    "burro",
    "fagshit",
    "twunt",
    "alligatorbait",
    "protestant",
    "n0bhead",
    "penishead",
    "faget",
    "dong",
    "tossing salad",
    "titfuck",
    "hoer*",
    "coitus",
    "raghead",
    "asscock",
    "peido",
    "ja1lbait",
    "fkbny",
    "oh-my-god",
    "furona",
    "abo",
    "doodlyfuck",
    "pusy",
    "feioso",
    "m0therfucker",
    "soviet",
    "poonany",
    "demonio",
    "niggled",
    "pickaninny",
    "dild0s",
    "pissflaps",
    "bitch",
    "mocky",
    "higgers",
    "oaf",
    "asshead",
    "suckass",
    "*fuck*",
    "gash-stabber",
    "addict",
    "hand job",
    "homo-sexual",
    "cumtart",
    "buttfucka",
    "bigbastard",
    "orgy",
    "one cup two girls",
    "bolcat",
    "shitfire",
    "conspiracy",
    "goddamnit",
    "fagg1t",
    "shitfuckhead",
    "shitlickers",
    "pussee",
    "assface",
    "doggie style",
    "pigfukker",
    "domination",
    "fuckfaces",
    "bitchings",
    "plonker",
    "felch",
    "swalow",
    "dickweeds",
    "puta",
    "bullshite",
    "penas",
    "niggas",
    "whop",
    "bullshit",
    "nobj0key",
    "wnker",
    "kumming",
    "fck",
    "bangbros",
    "diddle",
    "byatch",
    "fiddlyfuck",
    "beat the meat",
    "girly bits",
    "carruth",
    "doodlyfucks",
    "jizzstain",
    "penisbanger",
    "kikes",
    "fking",
    "givehead",
    "fubar",
    "fcukker",
    "ero",
    "preteen",
    "nigger*",
    "cyalis",
    "dump a load",
    "meatbeatter",
    "fuckmovie",
    "butt pirate",
    "masterbation",
    "fear",
    "fk bunny",
    "drug",
    "bacura",
    "deth",
    "panti",
    "fungus",
    "cummer",
    "oral",
    "nigg@z",
    "dix",
    "ball licking",
    "bomd",
    "nigasses",
    "daygo",
    "cawksucker",
    "nuke",
    "molestor",
    "dumbfuck",
    "f0ckers",
    "butt-munchers",
    "l3i+ch",
    "beat-off",
    "bi-sexual",
    "mooncricket",
    "h4x0r",
    "dipsh1tty",
    "nobjokeys",
    "s/h/i/t",
    "psycho",
    "xochota",
    "angie",
    "luckycammeltoe",
    "butthole",
    "fuks",
    "dikhead",
    "manhater",
    "god damnit",
    "mofuk",
    "dumbfucks",
    "pron",
    "crimes",
    "cocksmoke",
    "beeotch",
    "sexwhore",
    "basturd",
    "female squirting",
    "babies",
    "adult",
    "gay shit",
    "p3nisfcker",
    "jizzes",
    "fuckmehards",
    "japcrap",
    "juggalo",
    "boody",
    "zip in the wire",
    "naba",
    "ass monkey",
    "sextoys",
    "apeshite",
    "qweir",
    "cuntbollock",
    "ejaculation",
    "shit head",
    "fistfucker",
    "fucking asshole",
    "sh! +",
    "sambo",
    "buried",
    "shinola",
    "piss-artist",
    "debiloide",
    "cockmongruel",
    "doodoo",
    "acrotomophilia",
    "bisexual",
    "cuunt",
    "pansies",
    "moron",
    "bitchness",
    "son o bitch",
    "wichser",
    "crotchmonkey",
    "beatoff",
    "debil",
    "jailba!t",
    "packy",
    "bunny fucker",
    "twatface",
    "asslicker",
    "spix",
    "b1tchez",
    "cocksuccer",
    "radicals",
    "godammit",
    "whore",
    "kafir",
    "labia",
    "s.o.b.",
    "motherfucking",
    "nob jokey",
    "twatzilla",
    "lezzer",
    "shiester",
    "canadian",
    "sadis",
    "muthafucka",
    "crows",
    "shitbrain",
    "go to hell",
    "eunuch",
    "whitenigger",
    "tang",
    "curalho",
    "axewound",
    "assfuck3r",
    "pussless",
    "bullcrap",
    "manguaca",
    "fuckwits",
    "australian",
    "muffindiving",
    "filipina",
    "amateur",
    "ball sucking",
    "beaners",
    "shitbagger",
    "tinkle",
    "nobbyhead",
    "l3i + ch",
    "leprosa",
    "b1tchees",
    "sluts",
    "masturbate",
    "berk",
    "pula",
    "leproso",
    "bugfucker",
    "kawk",
    "intercourse",
    "crotchy",
    "bitchtits",
    "penisfvckers",
    "assfcker",
    "niggards",
    "j3rk",
    "tantra",
    "0rgasms",
    "make me come",
    "sucks",
    "angry",
    "bumblefuck",
    "skribz",
    "muthafecker",
    "fuckbags",
    "dogshits",
    "pric",
    "assklown",
    "beat your meat",
    "m@derfaker",
    "bestiality",
    "wanked",
    "jackarse",
    "motherfvcked",
    "shitheads",
    "pole sucker",
    "niguh",
    "assfker",
    "phuckings",
    "jack offs",
    "nofuckingway",
    "pthc",
    "mothafuckins",
    "trashbitches",
    "higg3r",
    "h00r",
    "sons of b1tches",
    "blow j",
    "cocksman",
    "gooch",
    "jiz",
    "sh1tty",
    "rice monkey",
    "fukkah",
    "goddamned",
    "caaak",
    "brexa",
    "chibumba",
    "mibun",
    "bible",
    "master-bate",
    "honkey",
    "vagina",
    "chickenshits",
    "penispuffer",
    "birdlock",
    "bum clat",
    "cornhole",
    "assrammer",
    "mulkku",
    "cunt ass",
    "bulldike",
    "knob3d",
    "fuccers",
    "sociopath",
    "cuksukka",
    "chifruda",
    "nigg4hs",
    "m0fos",
    "tallywacker",
    "dickmuncher",
    "pillu",
    "rere",
    "cyberfuc",
    "nigaboo",
    "knob eater",
    "r3t@rded",
    "fcuking",
    "booobs",
    "nonce",
    "sniggers",
    "douche-fag",
    "apeshit",
    "n1ggah",
    "doida",
    "assgoblin",
    "omigod",
    "baba-ovo",
    "whigger",
    "pissed off",
    "playgirl",
    "dickweed",
    "shitting",
    "horseshit",
    "wang",
    "packingfudgefucking",
    "f0cked",
    "ass eating boiolas",
    "spankthemonkey",
    "cawk",
    "butt-pirate",
    "creampie",
    "giant cock",
    "trojan",
    "fuckarounds",
    "whorehouse",
    "randy",
    "ohfuck",
    "shit fuck",
    "motherfvcker",
    "cockhed",
    "muther",
    "forked",
    "jizjuice",
    "schaffer",
    "fvckbunny",
    "fuckarow",
    "burn",
    "masterbat",
    "balls",
    "goddamnmuthafucker",
    "fucked",
    "spicfuck",
    "mulatto",
    "fucka",
    "jerkass",
    "gangbanger",
    "shitbugs",
    "cockblocker",
    "ratfucks",
    "shit for brains",
    "b00bz",
    "shiz",
    "buttfuck",
    "lalau",
    "fukkin",
    "puxasaco",
    "titjob",
    "pentelha",
    "donkyshits",
    "chocha",
    "disturbed",
    "roundeye",
    "slave",
    "jerkoff",
    "scallywag",
    "cok",
    "bitchs",
    "bombs",
    "fairies",
    "bullshitting",
    "fukin",
    "big tits",
    "fight",
    "n1g3rz",
    "asshopper",
    "faggot mofoes",
    "sodom",
    "daterape",
    "hummer",
    "color",
    "penthouse",
    "fingerfood",
    "puussy",
    "phungky",
    "pros",
    "motherfcking",
    "lusting",
    "fuchah",
    "shut the fuck up",
    "arse bandit",
    "scrubber",
    "stfu",
    "knobjokeys",
    "phucked",
    "fcuks",
    "arse-shagger",
    "fode",
    "slit",
    "mattressprincess",
    "bra",
    "analingus",
    "gfy",
    "fucking bastard",
    "fuck goblin",
    "heterosexual",
    "lovebone",
    "topless",
    "ecchi",
    "marijuana",
    "fuckits",
    "sh1ts",
    "rapist",
    "backdoor",
    "dipshitter",
    "quickie",
    "ejakulate",
    "dickslapper",
    "fellatio aficionado",
    "rabudao",
    "tittiefucker",
    "pisses",
    "phukker",
    "b1+ch",
    "bumfucks",
    "lotion",
    "dope",
    "mothafuckazzes",
    "stroke",
    "smeg",
    "piss artist",
    "chereca",
    "shite",
    "ayir",
    "cumqueen",
    "twatt",
    "queaf",
    "grope",
    "futhamucka",
    "wazzock",
    "paca",
    "style doggy",
    "phags",
    "cockblockers",
    "tadger",
    "how to kill",
    "slutt",
    "excrement",
    "bitching",
    "fckin",
    "tongue in a",
    "cocksucc",
    "porra",
    "smut",
    "coolie",
    "gangbangs",
    "clusterfucker",
    "buttfucks",
    "g00k",
    "samckdaddy",
    "babaovo",
    "picao",
    "girls",
    "twatwaffle",
    "fvck",
    "a55",
    "sixty-nine",
    "get fucked",
    "skankwhore",
    "chinky",
    "n1gg@hs",
    "tubgirl",
    "shi+e",
    "dipshidiot",
    "fagz",
    "fucker off",
    "upskirt",
    "fukwhore",
    "childrens",
    "cholo",
    "lesbo",
    "slutz",
    "juggs",
    "penisfuckers",
    "munging",
    "pixie",
    "shit fucker",
    "chinese",
    "transsexual",
    "facefuckers",
    "polak",
    "buttfucker",
    "godd@amn",
    "nigg@hs",
    "slanteye",
    "prat",
    "niglet",
    "ladiboy",
    "peepshpw",
    "kooch",
    "nigers",
    "bitchasses",
    "5h17",
    "cuntfucks",
    "fuckahs",
    "crotchjockey",
    "blacky",
    "deep throat",
    "beat off",
    "hoar",
    "trailertrash",
    "fuckmachine",
    "munter",
    "nunfuckers",
    "ladyboyz",
    "fugly",
    "bullshi",
    "nipples",
    "sh1t",
    "wank",
    "packi",
    "shawtypimp",
    "goddamn son of a bitch",
    "church",
    "motherfcked",
    "puxa-saco",
    "shitties",
    "zipperhead",
    "mufflikcer",
    "funfuck",
    "sheet",
    "motherfucca",
    "syphilis",
    "wetbacks",
    "swine fucker",
    "fuckya",
    "fingerfucked",
    "fuckwhores",
    "kiunt",
    "mothafucc",
    "tranny",
    "cockshit",
    "shi+",
    "dick",
    "jiggaboos",
    "suck off",
    "twatty",
    "shitz",
    "scumbag",
    "killer",
    "shitlist",
    "c*nts",
    "shitpots",
    "homo asses",
    "jail bait",
    "omygod",
    "shitcunt",
    "fuckshit",
    "minger",
    "cntz",
    "bassterds",
    "porn",
    "you idiot",
    "dumshit",
    "cocksucks",
    "shit-stuffers",
    "damned",
    "phuku",
    "palm jockey",
    "dickjuice",
    "nob",
    "fukken",
    "jugs",
    "ash0les",
    "rolinha",
    "sonofabitch",
    "women rapping",
    "purinapricness",
    "nigg4h",
    "japanese",
    "hore",
    "bukkake",
    "she-male",
    "penisfucker",
    "jade",
    "shitefulls",
    "pikey",
    "masochist",
    "mothafvcked",
    "pissed",
    "dickhead",
    "stupid hoe",
    "niggass",
    "esporrada",
    "fucker",
    "lezzie",
    "choad",
    "chuj",
    "cyberslimer",
    "knobjocky",
    "payo",
    "fukcs",
    "kusi",
    "mouliewop",
    "spig",
    "trashb1tch",
    "pull the pud",
    "mo-fo",
    "geni",
    "girlyboy",
    "brea5t",
    "sexhouse",
    "abuse",
    "f@cker bunny",
    "wanking",
    "trasherbitchs",
    "fuckfriends",
    "shitfk",
    "schlampe",
    "attack",
    "packie",
    "clitoris",
    "dang",
    "argie",
    "lezz",
    "piss off fuckhead",
    "thirdleg",
    "fuck head",
    "knobheads",
    "bastardo",
    "mofuccers",
    "g@yshit",
    "fuckpuppet",
    "nudger",
    "tittie",
    "sonna bitch",
    "piss face",
    "dickmilk",
    "paspalha",
    "ragheads",
    "ikey",
    "dumb fuck",
    "clogwog",
    "doosh",
    "fatfucks",
    "ass fucking boiolas",
    "goddamn",
    "arse gobbler",
    "pedobear",
    "cocklickers",
    "teat",
    "erectoplasm",
    "fuck faces",
    "funeral",
    "assbagger",
    "cuntlick",
    "mutha fukkah",
    "fucktards",
    "cyberfvcks",
    "bunga",
    "homobangers",
    "beyotch",
    "dominatricks",
    "arse-hole",
    "paedophile",
    "cigarette",
    "sniggered",
    "motha",
    "w4nk3r",
    "handjob",
    "feces",
    "poopchute",
    "asslovers",
    "cyberfuccs",
    "assault",
    "virgin",
    "god dammit",
    "pimpis",
    "libido",
    "god damned",
    "fag0t",
    "punk ass mofoes",
    "fuk1ng",
    "bitchhole",
    "harry palms",
    "fcked",
    "bitches",
    "slopehead",
    "ladyb0i",
    "hoe",
    "dickskin",
    "peter",
    "poop chute",
    "biotches",
    "coochy",
    "bollocks",
    "mindfuckings",
    "knob jockey",
    "fukker",
    "krappy",
    "splittail",
    "phukshit",
    "assmonkey",
    "fuckyas",
    "phukeds",
    "fuckstar",
    "arse hole",
    "fuccing",
    "jelly donut",
    "yed",
    "fuckdollies",
    "cyberfcks",
    "urophilia",
    "nutsack",
    "shitstains",
    "cock-suckers",
    "phuc",
    "cawkmuncher",
    "boobs",
    "shittier",
    "cuntbag",
    "naked",
    "b1tch",
    "muddafukkas",
    "nazi",
    "g0ddamnit",
    "massterbait",
    "finger fuck",
    "farted",
    "peter puffer",
    "2 girls 1 cup",
    "fuckpuppets",
    "fudecao",
    "bumfuck",
    "gaysian",
    "nigguh",
    "huge fat",
    "shitfck",
    "mushroom tip",
    "numpty",
    "coons",
    "dog fuck",
    "spik",
    "esporrado",
    "renob",
    "peeenus",
    "whoars",
    "cornholes",
    "dogfucks",
    "fuckings",
    "footfuckers",
    "bassturd",
    "motherfuckers",
    "doom",
    "abbo",
    "slag",
    "motherfukker",
    "snownigger",
    "n1ggers",
    "gosh darn",
    "chinavirus",
    "bogshit",
    "threeway",
    "phuccing",
    "god",
    "cretino",
    "interracial",
    "phuking",
    "shitfaced",
    "sexing",
    "knob-face",
    "biatch",
    "testical",
    "prick-gobbler",
    "whiskey",
    "darkie",
    "mothafucks",
    "jerks",
    "titfucker",
    "shitbag",
    "godd@mnit",
    "mofucckers",
    "imbecil",
    "vorarephilia",
    "pisspig",
    "dumass",
    "f@g",
    "motherfucker",
    "sandnigger",
    "henshits",
    "kondums",
    "fckcum",
    "m@derfuckers",
    "c*ntface",
    "5hit",
    "niggazzes",
    "sand nigger",
    "phuckin",
    "orifiss",
    "everfucking",
    "jack off",
    "piroca",
    "mutherfuckers",
    "fvck you",
    "busseta",
    "dike*",
    "dipsh1t",
    "sick",
    "mofukkas",
    "dendrophilia",
    "cumquats",
    "fistfuckings",
    "c0cksucked",
    "erotic",
    "phaggots",
    "ratfuck",
    "sons-of-bitches",
    "ethiopian",
    "mof0",
    "upskirts",
    "muffindivers",
    "hodgie",
    "m@derfuck",
    "fatasses",
    "tickle the pickle",
    "dicks",
    "blow jobs",
    "piky",
    "cockqueen",
    "penuus",
    "cajones",
    "fucking retard",
    "fucktart",
    "boob",
    "birdshits",
    "polac",
    "shemale",
    "whorefucker",
    "g@ylord",
    "dickmonger",
    "girl on top",
    "jizzy",
    "b!tch",
    "culhao",
    "faggit",
    "niggers",
    "dicklicks",
    "whites",
    "sh1theads",
    "jerk",
    "gaiata",
    "lovemaking",
    "beshitted",
    "catshits",
    "dickface",
    "shitstain",
    "bastardz",
    "iblowu",
    "bellend",
    "cock-sucker",
    "ladyboys",
    "murder",
    "ejaculate",
    "m0f0",
    "shota",
    "cocksmith",
    "panooch",
    "cachorra",
    "bitchslaps",
    "gang bang",
    "wormshit",
    "hook",
    "cuntlickings",
    "muthafuckas",
    "ape shit",
    "faggs",
    "dike",
    "bitchy",
    "fu(*",
    "teste",
    "knobends",
    "bender",
    "flamers",
    "alaskan pipeline",
    "bitchlike",
    "sextogo",
    "shitasses",
    "cockass",
    "jizz-jockey",
    "fuq",
    "assblaster",
    "cunthole",
    "bixa",
    "shittyfuckface",
    "bosta",
    "brown showers",
    "dicktickler",
    "fckking",
    "fuk*",
    "godshits",
    "dragqueen",
    "scummy",
    "danged",
    "shit face",
    "diddlyfuck",
    "goddammit",
    "mound of venus",
    "sleezebag",
    "pu$sy",
    "nig",
    "german",
    "huevon",
    "niggard",
    "sh1tter",
    "paspalho",
    "mothafuckasses",
    "henshit",
    "muie",
    "pot",
    "wise ass",
    "twobitwhore",
    "gaybob",
    "omg",
    "arseholes",
    "scrote",
    "biotchez",
    "pussy fucker",
    "gaylords",
    "knobjockies",
    "turdcutter",
    "girl on",
    "nut sack",
    "liberal",
    "douchewaffle",
    "shites",
    "panties",
    "oldfucker",
    "nigg@zzes",
    "fenda",
    "holestuffer",
    "bull shit",
    "cockeater",
    "cumbubble",
    "cumshot",
    "buttmuncher",
    "oven dodger",
    "besta",
    "trisexual",
    "knobender",
    "shitface",
    "cretina",
    "commie",
    "rearentry",
    "fuckmes",
    "joyshit",
    "m0f0s",
    "s_h_i_",
    "nikker",
    "cotton picker",
    "muff",
    "thefuck",
    "homossexual",
    "bi + ch",
    "n1ggas",
    "fuckaroo",
    "fukking",
    "vulva",
    "rimjaw",
    "titt*",
    "f@ck",
    "basterds",
    "dafuq",
    "shtfuk",
    "laid",
    "oldfucks",
    "american",
    "racist",
    "buttpirate",
    "boobies",
    "cawk muncher",
    "welcher",
    "skeet",
    "nobjockies",
    "orifice",
    "mofo ass",
    "h0re",
    "cockknob",
    "btch",
    "sacana",
    "tnt",
    "f@gs",
    "communist",
    "absofuckinglutely",
    "dies",
    "pimmel",
    "quim",
    "knobendy",
    "cyberfck",
    "murderer",
    "slanteyeshit",
    "retarded",
    "tyke",
    "piss*",
    "babe",
    "skankz",
    "shity",
    "cagone",
    "nickker",
    "flydie",
    "sweetness",
    "fuckfreaks",
    "kanker*",
    "assbite",
    "bitch*",
    "c0cks",
    "reestie",
    "kums",
    "blackout",
    "chifrudo",
    "rimjob",
    "cobblers",
    "@sshole",
    "strip club",
    "kumbubble",
    "l@dyboy",
    "poo",
    "damnation",
    "arse-fucker",
    "auto erotic",
    "assjacker",
    "cock sucking boiolas",
    "fudge packer",
    "lesbayn",
    "feiosa",
    "sonofbitches",
    "motherfuckings",
    "vittu",
    "soab",
    "trashbitch",
    "faggot nobjockies",
    "fuck you",
    "getiton",
    "fellatio",
    "0ral seks",
    "punta",
    "pusslicker",
    "hole",
    "cowshit",
    "d1cksukka",
    "limey",
    "fucktard",
    "piece of shit",
    "gross",
    "dicklickers",
    "c0x",
    "fucknut",
    "yellow showers",
    "twink",
    "pocho",
    "broad",
    "how to murder",
    "rim job",
    "jerking off",
    "sexual",
    "fxcker",
    "scheiss*",
    "fuking",
    "assjockey",
    "upthebutt",
    "negroid",
    "w4nker",
    "boong",
    "w00se",
    "transexual",
    "cumfest",
    "pimper",
    "fckked",
    "higga",
    "dupa",
    "f4nny",
    "kinbaku",
    "xoxota",
    "ratshits",
    "fuckyous",
    "ohmigod",
    "sumbitch",
    "nympho",
    "cornuda",
    "ma5terbate",
    "kiddy touch",
    "dickhole",
    "whorefuckers",
    "nookey",
    "eatballs",
    "xaninha",
    "sexxx",
    "assfukkerz",
    "u cock",
    "fuccks",
    "punhetao",
    "dolcett",
    "codger",
    "anal pirate",
    "helvete",
    "urinary",
    "cagao",
    "buttplug",
    "s-lut",
    "fuckedups",
    "shitehead",
    "fucksome",
    "stupidasses",
    "dickwod",
    "shitbird",
    "cockmonkey",
    "nikk3r",
    "jizzed",
    "mondrongo",
    "dickslap",
    "fuckass",
    "furo",
    "niggerz",
    "mutha fukah",
    "fuckedup",
    "jism",
    "arsewipe",
    "\ud83d\udd95",
    "piru",
    "fcka",
    "fag hag",
    "dingleberry",
    "nigga",
    "fuckem",
    "radical",
    "ass fucking nob jokeys",
    "ass-bandit",
    "dago",
    "bumblefucks",
    "mothafuckazs",
    "chink",
    "jiggerboo",
    "moleca",
    "wrinkled starfish",
    "shlong",
    "shithole",
    "venus mound",
    "violet blue",
    "urine",
    "tonguetramp",
    "shaved pussy",
    "butt fuck",
    "slut",
    "mofcker",
    "cuntasaurus rex",
    "jerks off",
    "mggor",
    "n0bj0cky",
    "fudgefucker",
    "raping",
    "fuckbutt",
    "negr0",
    "dumbarrassed",
    "darkfuck",
    "coward",
    "g0ddamn",
    "ramrod",
    "feg",
    "overfuckingjoyed",
    "assfucker",
    "wuss",
    "nunfucker",
    "hardcoresex",
    "fuckmonkey",
    "asses",
    "twat waffle",
    "shitass",
    "big black",
    "fistfucking",
    "cock jockey",
    "twatlips",
    "cummings",
    "fvckers",
    "willy-whacker",
    "nigg3r",
    "shagger",
    "arse",
    "hillbillies",
    "fitt*",
    "dommes",
    "asskiss",
    "uck",
    "spics",
    "execution",
    "died",
    "fuckit",
    "nip",
    "p3nisfcukers",
    "ballsack",
    "kid",
    "nigger",
    "prost-bulo",
    "rachadinho",
    "fucking",
    "trousersnake",
    "wop*",
    "conservative",
    "fuckbuddies",
    "freakfuck",
    "chickenshit",
    "butt",
    "cocktail",
    "strapon",
    "cock sucking nob jokeys",
    "weenie",
    "mothafucced",
    "gay ass",
    "beast",
    "pisshead",
    "sexx",
    "heck",
    "fucking hell",
    "shemales",
    "bugshit",
    "loony",
    "boonie",
    "muhfucking",
    "assfook",
    "motha fukker",
    "addicts",
    "junglebunny",
    "muthafukka",
    "poof",
    "fucknuckle",
    "uterus",
    "nig-nag",
    "mamhoon",
    "fkings",
    "fuckup",
    "mother fukker",
    "chinaman",
    "biteme",
    "nobs",
    "punany",
    "bell end",
    "picka",
    "niggardlinesss",
    "knobjokey",
    "fuckfriend",
    "puntang",
    "d!ldo",
    "queerhole",
    "orga",
    "mothafuckin",
    "omorashi",
    "pussy licking",
    "cuntlicker",
    "flydye",
    "torture",
    "strappado",
    "ass",
    "whorebag",
    "fuckathon",
    "shipdit",
    "fagging",
    "@55",
    "fuckaroos",
    "c*nty",
    "broads",
    "harem",
    "knobeads",
    "buggered",
    "remela",
    "sh1tt",
    "rump",
    "rigger",
    "lesbian",
    "slimebucket",
    "godshit",
    "prickhead",
    "greaser",
    "jeez",
    "shitboxes",
    "taking the piss",
    "gaydo",
    "pr0n",
    "drunken",
    "dragqween",
    "glazeddonut",
    "knobendz",
    "sifilis",
    "spierdalaj",
    "arschloch",
    "enemy",
    "*dyke",
    "ragtard",
    "tezudo",
    "cockknoker",
    "phuck",
    "motherfxck",
    "butt-fucking-bandit",
    "fuckhers",
    "shiat",
    "nymph",
    "bitchers",
    "nobheads",
    "kkk",
    "double penetration",
    "sexslave",
    "shitmouse",
    "cazzo",
    "bebum",
    "fvckin",
    "shitassfucker",
    "lovepistol",
    "spermhearder",
    "cyberfucs",
    "shiteblimps",
    "cockgobbler",
    "assfvcker",
    "xana",
    "rat baztad",
    "ladroeira",
    "genital",
    "blue waffle",
    "faeces",
    "shitfacefuck",
    "headfucks",
    "freefuck",
    "minge",
    "fuckah",
    "shitbrains",
    "dickvag",
    "shiting",
    "s.o.b.s",
    "demon",
    "hoore",
    "cunt lick",
    "double dong",
    "piker",
    "homicide",
    "motherfukkah",
    "fuckwhore",
    "dune coon",
    "hosejob",
    "masterb8",
    "fistfuck",
    "asslicks",
    "k!ke",
    "pearlnecklace",
    "group sex",
    "hoe-asses",
    "phukk",
    "cooter shooting",
    "cripple",
    "lady-boy",
    "fick",
    "puke",
    "focker",
    "lemon party",
    "fuckars",
    "sk@nkz",
    "failure",
    "towelshithead",
    "cuntz",
    "ch1nk",
    "klitoris",
    "shet",
    "fuckknobs",
    "useless fucker",
    "ass fecker",
    "cabron",
    "scrotum",
    "shiesterfucks",
    "shmale",
    "coonies",
    "5kank",
    "shitsplat",
    "fuckink",
    "nasty",
    "fuckwhit",
    "motherfuckkers",
    "mfers",
    "shitfit",
    "niggle",
    "dingleberries",
    "trashbtch",
    "cockfight",
    "queerbait",
    "puuke",
    "cretin",
    "bunghole",
    "sexfarm",
    "gayness",
    "casseta",
    "ashole",
    "scissoring",
    "sh1td1ck",
    "toilet",
    "viadao",
    "shitola",
    "kunnilingus",
    "crotch fiddler",
    "farty",
    "xavasca",
    "ar5ehole",
    "quashie",
    "rautenberg",
    "fack",
    "pussylover",
    "trots",
    "tezao",
    "paki",
    "cherrypopper",
    "ladrona",
    "phucchead",
    "fu",
    "bestial",
    "hooker",
    "nigg@",
    "cockblocks",
    "god damn it",
    "clunge",
    "crapper",
    "son of a bitch",
    "buttcheeks",
    "kootch",
    "nude",
    "horseshits",
    "dickwads",
    "4r5ed",
    "mufdive",
    "beastial",
    "batshite",
    "fart-fucker",
    "peckerwood",
    "m0thafucker",
    "dickbrain",
    "mockey",
    "snatchpatch",
    "fuck your mother",
    "trasherbitch",
    "mifuckinlady",
    "motherfcks",
    "pornking",
    "bomb",
    "dykes",
    "skanks",
    "cooterpuffing",
    "dolt",
    "girlieboy",
    "olhota",
    "pr1ck",
    "chocolate rosebuds",
    "niggaz",
    "swallower",
    "limpdick",
    "knob",
    "biches",
    "suicide girls",
    "bosseta",
    "arses",
    "shitmouses",
    "poop",
    "wimp",
    "mickeyfinn",
    "f@k",
    "ja!lbait",
    "fagg0t",
    "pussylips",
    "testicle*",
    "pudd",
    "magicwand",
    "phvckings",
    "monkleigh",
    "whafuck",
    "ohgod",
    "trollop",
    "dipstick",
    "cancer",
    "mothafuckers",
    "son-of-a-bitch",
    "femdom",
    "mothafuccing",
    "waysted",
    "cocky",
    "kumbullbe",
    "motherfvckers",
    "gokkun",
    "knober",
    "shitfuck",
    "cunt lips",
    "hooters",
    "dipshat",
    "milf",
    "azzhole",
    "kuksuger",
    "urinate",
    "aroused",
    "viada",
    "molester",
    "peckerhead",
    "n1gg@",
    "fuckins",
    "sl@nteye",
    "analannie",
    "l3sbi4n",
    "otaria",
    "boceta",
    "fagtard",
    "hot carl",
    "grelinho",
    "suckmyass",
    "cuntsuckers",
    "n1gger",
    "boquete",
    "cyberfucking",
    "vaca",
    "bimbos",
    "ass-fuckers",
    "mofuckkas",
    "dogging",
    "turd",
    "hoser",
    "motherfuckin",
    "ballsacks",
    "jiggaboo",
    "pornflick",
    "eat my ass",
    "nigglings",
    "shithouse",
    "bigass",
    "cocksuccas",
    "l3itches",
    "africa",
    "dumbasses",
    "shithapens",
    "mutherfucker",
    "we1back",
    "fuckable",
    "camgirl",
    "barely legal",
    "cockteases",
    "blonde action",
    "fuckdolly",
    "cnts",
    "fuckies",
    "pimped",
    "russkie",
    "camel jockey",
    "drunk",
    "schizo",
    "chickslick",
    "mothafukkah",
    "bum-driller",
    "faggot",
    "pedos",
    "mideast",
    "pussywhipped",
    "knob-gobbler",
    "cocsuck",
    "african",
    "bdsm",
    "mof0es",
    "cruz-credo",
    "scumfuck",
    "homosexual",
    "neonazi",
    "crackwhore",
    "piss pig",
    "raper",
    "d1ck",
    "cuntface",
    "stagg",
    "qweerz",
    "wank3r",
    "niggerhole",
    "asswad",
    "molestation",
    "niggah",
    "fag1t",
    "fagbag",
    "slaughter",
    "tea bagging",
    "anus",
    "prega",
    "gay",
    "fuccs",
    "funbags",
    "double dick",
    "bugfuck",
    "nutfucker",
    "fuckstick",
    "shaved beaver",
    "feck arse",
    "hell",
    "ass-hole",
    "playboy",
    "rachado",
    "fatfucker",
    "coondog",
    "goodpoop",
    "poverty",
    "nigr",
    "remains",
    "wankbastard",
    "suckmydick",
    "fuckoffs",
    "pillow biter",
    "fornicate",
    "sexy",
    "nigs",
    "bostana",
    "fuckmovies",
    "cunt licker",
    "shitey",
    "clusterfucks",
    "jizz",
    "assbandit",
    "queer",
    "shitheadfuckface",
    "chode",
    "skankey",
    "mudderfukker",
    "hijacker",
    "assfck",
    "egua",
    "pigshit",
    "seppo",
    "m0therfuckeds",
    "bombers",
    "w@nker",
    "porch monkey",
    "muthafucks",
    "osama",
    "jagoff",
    "easyslut",
    "raging boner",
    "damnit",
    "fuggerz",
    "mutha fucka",
    "cumguzzler",
    "stabbed",
    "assfukka",
    "nooner",
    "bollock",
    "peinus",
    "henhouse",
    "fookuh",
    "f u c k",
    "markasses",
    "faggitt",
    "sixtyniner",
    "shytfeisterfuck",
    "l3itch",
    "fuckyou",
    "jerk-offs",
    "fag*",
    "slutbag",
    "lezbo",
    "booty call",
    "pendy",
    "dafuck",
    "cachorro",
    "towelhead",
    "pillow-biter",
    "insest",
    "shittyful",
    "buttbang",
    "fannyfucker",
    "babaca",
    "basterdz",
    "chinese-virus",
    "pau",
    "butchdike",
    "motherfacking",
    "muthafukker",
    "cocknose",
    "kusi*",
    "ethical slut",
    "bronha",
    "god-dam",
    "ass-pirate",
    "groe",
    "knobhead",
    "fuckinrights",
    "shitpot",
    "feioza",
    "farting",
    "pussycat",
    "trashybitches",
    "thirdeye",
    "gonorrehea",
    "tushy",
    "cockfucker",
    "wankies",
    "fannyflaps",
    "pizda",
    "m0ngoloid",
    "wog",
    "butthead",
    "sob",
    "sh1tsome",
    "muppet",
    "shipal",
    "lezzo",
    "retard",
    "beastality",
    "phucker",
    "schlong",
    "strapons",
    "fellator",
    "reefer",
    "shitfired",
    "b00b*",
    "dicksmoker",
    "slutwhore",
    "assmunch",
    "faen",
    "unclefucker",
    "cockmuncher",
    "cocktease",
    "sheeeet",
    "d1ckheads",
    "nob jockey",
    "man meat",
    "orgasim;",
    "felcher",
    "footstar",
    "european",
    "sharmute",
    "bewbs",
    "assfucks",
    "mecha fag",
    "dicksucker",
    "satan",
    "nymphomania",
    "ass eating nob jokeys",
    "spook",
    "yaoi",
    "fedorenta",
    "motherfuckkas",
    "hardon",
    "escrota",
    "jew",
    "shitcans",
    "propaganda",
    "safada",
    "batshits",
    "israeli",
    "fuckbag",
    "cocksuckas",
    "shitings",
    "pollock",
    "defecate",
    "bollox",
    "dick-gobbler",
    "paska",
    "assfkr",
    "skank",
    "knife",
    "peepshow",
    "cockmonger",
    "jigaboos",
    "oh my god",
    "faggot nob jokeys",
    "poofter",
    "shitfudgefucker",
    "corno",
    "suck my cock",
    "felacao",
    "scut",
    "fudido",
    "mastrabator",
    "hamas",
    "jerk-0ff",
    "coonie",
    "kuk",
    "4r5e",
    "virginbreaker",
    "hentai",
    "sandm",
    "cocksucked",
    "jiggyboo",
    "oriface",
    "goldenshower",
    "dork",
    "fat",
    "cameltoe",
    "racha",
    "buca",
    "nimphomania",
    "vibrator",
    "dink",
    "douche canoe",
    "caralho",
    "face fuck",
    "pubes",
    "pusse",
    "axe wound",
    "you cock",
    "hobo",
    "shiteater",
    "tezuda",
    "fckedup",
    "mega fag",
    "vagabunda",
    "mother fukah",
    "liquor",
    "cyberfucker",
    "motherfuker",
    "cocks",
    "pocketpool",
    "prick-face",
    "masterbations",
    "bugger off",
    "evl",
    "eatme",
    "nlggor",
    "pissin",
    "barface",
    "biotch",
    "goy",
    "masterbat*",
    "jap",
    "jisim",
    "dick smoker",
    "niggir",
    "jerk-off",
    "teez",
    "bisca",
    "difunto",
    "faith",
    "cockmongler",
    "bitchez",
    "buttmunch",
    "cunillingus",
    "kock",
    "pommie",
    "sh!t*",
    "pistol",
    "jizzum",
    "shemal3",
    "jackoff",
    "fuckathons",
    "diddlyshits",
    "dipshits",
    "gyppie",
    "shithappens",
    "darky",
    "jiggas",
    "spunky",
    "soppy bollucks",
    "cyberfukk",
    "cacker",
    "fatso",
    "buceta",
    "dinks",
    "pussy lick",
    "nastywhore",
    "fxck",
    "fckk",
    "bondage",
    "niggress",
    "wtf",
    "furado",
    "mijada",
    "donkyshit",
    "pole smoker",
    "kneegrows",
    "stupidfuckers",
    "cassete",
    "dog fucker",
    "reject",
    "sex",
    "cl1t",
    "sweetfucked",
    "paspalhao",
    "fuckheads",
    "pom",
    "fukkers",
    "dick-head",
    "nob jokeys",
    "hiscock",
    "gaysex",
    "carpet muncher",
    "reacharound",
    "your ass",
    "hapa",
    "vagiina",
    "kaffer",
    "palesimian",
    "nig-nog",
    "niggaracci",
    "hui",
    "livesex",
    "rape",
    "fart",
    "flipping",
    "niiger",
    "hardcore",
    "jiggs",
    "w0p",
    "troxa",
    "j-offs",
    "lipshits",
    "perse",
    "sphencter",
    "mongoloid",
    "barf",
    "wanky",
    "burra",
    "butt-fucker",
    "foda",
    "masokist",
    "herpes",
    "muthafuckker",
    "tarado",
    "fanculo",
    "blow your l",
    "pudboy",
    "wigger",
    "phuks",
    "gypo",
    "mofoshit",
    "gypp",
    "sum of a bitch",
    "chingchong",
    "poorwhitetrash",
    "bugshits",
    "fkker",
    "yankee",
    "b1tching",
    "swine",
    "kinkster",
    "knulle",
    "masstrbait",
    "clits",
    "willies",
    "cock*",
    "dogfucked",
    "tittywank",
    "cock licker",
    "kraut",
    "pierdol*",
    "assfukah",
    "@ssfvcker",
    "black",
    "goddam",
    "ass fucker",
    "vajayjay",
    "nambla",
    "pube",
    "murdered",
    "anal",
    "fuuck",
    "shitforbrains",
    "fcuker",
    "bulldyke",
    "dirty pillows",
    "spaghettibender",
    "lezbe",
    "sonsofbitches",
    "fccuker",
    "mams",
    "poontang",
    "bollock*",
    "crow",
    "orgies",
    "crazy mofos",
    "fingerfucker",
    "pussi",
    "yellowman",
    "feltcher",
    "fukheads",
    "donkey punch",
    "penus",
    "krap",
    "joyshits",
    "lmfao",
    "dyke",
    "shitdick",
    "dvda",
    "skullfuck",
    "mother fukkah",
    "wh0r3",
    "booooobs",
    "puzzy",
    "s_h_i_t",
    "death",
    "fked",
    "mothfck",
    "gyppy",
    "bch",
    "jacktheripper",
    "muncher",
    "cuntrag",
    "merd*",
    "dumbass mothafuckers",
    "fatfuckers",
    "c0xux0r",
    "masterbat3",
    "s hit",
    "fatfuck",
    "gob",
    "shitspitter",
    "darkshit",
    "kinky",
    "aboe",
    "fckyeah",
    "wank3rs",
    "shitload",
    "fucca",
    "motherfuckingshit",
    "russki",
    "asscowboy",
    "lowlife",
    "bugfucking",
    "idiota",
    "mothafuckaz",
    "shitfaces",
    "cunilingus",
    "n1gga",
    "asshol3",
    "lingerie",
    "spooge",
    "nigg",
    "timber nigger",
    "negga",
    "fuckbrain",
    "pentelho",
    "fcking",
    "wankjob",
    "kum",
    "cameljockey",
    "shiesterfuckface",
    "fuckinnuts",
    "arrse"
]

export { toxicPhrases }
