import { UrlStatus } from '@src/shared/types/UrlStatus';
import { PrrCategory } from '@src/shared/types/PrrCategory';
import { PrrLevel } from '@src/shared/types/PrrLevel';

export class ZveloCategoryCodes {
    private static readonly CATEGORIES_CODES = {
        '10001': {
            level: PrrLevel.ONE,
            key: 'sex_education',
            category: PrrCategory.SEX_EDUCATION,
            categoryName: 'Sex Education',
            name: 'Abortion',
            status: UrlStatus.ALLOW,
        },
        '10002': {
            level: PrrLevel.ONE,
            key: 'sex_education',
            category: PrrCategory.SEX_EDUCATION,
            categoryName: 'Sex Education',
            name: 'Abortion Pro Choice',
            status: UrlStatus.ALLOW,
        }, // because of green color
        '10003': {
            level: PrrLevel.ONE,
            key: 'sex_education',
            category: PrrCategory.SEX_EDUCATION,
            categoryName: 'Sex Education',
            name: 'Abortion Pro Life',
            status: UrlStatus.ALLOW,
        }, // because of green color
        '10004': {
            level: PrrLevel.ONE,
            key: 'inappropriate_for_minors',
            categoryName: 'Inappropriate for Minors',
            category: PrrCategory.INAPPROPRIATE_FOR_MINORS,
            name: 'Child Inappropriate',
            status: UrlStatus.ALLOW,
        }, // because of green color
        '10005': {
            level: PrrLevel.ONE,
            key: 'gambling',
            categoryName: 'Gambling',
            category: PrrCategory.GAMBLING,
            name: 'Gambling',
            status: UrlStatus.BLOCK,
        },
        '10006': {
            level: PrrLevel.ONE,
            key: 'sex_education',
            category: PrrCategory.SEX_EDUCATION,
            categoryName: 'Sex Education',
            name: 'Gay, Lesbian or Bisexual',
            status: UrlStatus.BLOCK,
        },
        '10009': {
            level: PrrLevel.ONE,
            key: 'adult_sexual_content',
            categoryName: 'Adult Sexual Content',
            category: PrrCategory.ADULT_SEXUAL_CONTENT,
            name: 'Pornography',
            status: UrlStatus.BLOCK,
        },
        '10011': {
            level: PrrLevel.ONE,
            key: 'adult_sexual_content',
            categoryName: 'Adult Sexual Content',
            category: PrrCategory.ADULT_SEXUAL_CONTENT,
            name: 'R-Rated',
            status: UrlStatus.BLOCK,
        },
        '10012': {
            level: PrrLevel.ONE,
            key: 'adult_sexual_content',
            categoryName: 'Adult Sexual Content',
            category: PrrCategory.ADULT_SEXUAL_CONTENT,
            name: 'Sex & Erotic',
            status: UrlStatus.BLOCK,
        },
        '10013': {
            level: PrrLevel.ONE,
            key: 'sex_education',
            category: PrrCategory.SEX_EDUCATION,
            categoryName: 'Sex Education',
            name: 'Sex Education',
            status: UrlStatus.ALLOW,
        },
        '10014': {
            level: PrrLevel.ONE,
            key: 'tobacco',
            categoryName: 'Tobacco',
            category: PrrCategory.DRUGS_ALCOHOL_TOBACCO,
            name: 'Drug, Alcohol or Tobacco Related',
            status: UrlStatus.BLOCK,
        },
        '10016': {
            level: PrrLevel.THREE,
            key: 'Violence',
            categoryName: 'Violence',
            category: PrrCategory.VIOLENCE,
            name: 'Violence',
            status: UrlStatus.BLOCK,
        },
        '10017': {
            level: PrrLevel.THREE,
            key: 'weapons',
            categoryName: 'Weapons',
            category: PrrCategory.WEAPONS,
            name: 'Weapons',
            status: UrlStatus.BLOCK,
        },
        '10018': {
            level: PrrLevel.THREE,
            key: 'inappropriate_for_minors',
            categoryName: 'Inappropriate for Minors',
            category: PrrCategory.INAPPROPRIATE_FOR_MINORS,
            name: 'Aggressive - Other',
            status: UrlStatus.BLOCK,
        },
        '10074': {
            level: PrrLevel.THREE,
            key: 'criminal_malicious',
            category: PrrCategory.CRIMINAL_MALICIOUS,
            categoryName: 'Criminal/Malicious',
            name: 'Child Abuse Images',
            status: UrlStatus.BLOCK,
        },
        '10075': {
            level: PrrLevel.THREE,
            key: 'criminal_malicious',
            category: PrrCategory.CRIMINAL_MALICIOUS,
            categoryName: 'Criminal/Malicious',
            name: 'Criminal Skills',
            status: UrlStatus.BLOCK,
        },
        '10076': {
            level: PrrLevel.ONE,
            key: 'inappropriate_for_minors',
            categoryName: 'Inappropriate for Minors',
            category: PrrCategory.INAPPROPRIATE_FOR_MINORS,
            name: 'Hacking',
            status: UrlStatus.BLOCK,
        },
        '10077': {
            level: PrrLevel.ONE,
            key: 'hate_speech',
            categoryName: 'Hate Speech',
            category: PrrCategory.HATE_SPEECH,
            name: 'Hate Speech',
            status: UrlStatus.BLOCK,
        },
        '10078': {
            level: PrrLevel.ONE,
            key: 'drugs_alcohol_tobacco',
            category: PrrCategory.DRUGS_ALCOHOL_TOBACCO,
            categoryName: 'Drugs, Alcohol, or Tobacco Related',
            name: 'Illegal Drugs',
            status: UrlStatus.BLOCK,
        },
        '10079': {
            level: PrrLevel.ONE,
            key: 'drugs_alcohol_tobacco',
            category: PrrCategory.DRUGS_ALCOHOL_TOBACCO,
            categoryName: 'Drugs, Alcohol, or Tobacco Related',
            name: 'Marijuana',
            status: UrlStatus.BLOCK,
        },
        '10080': {
            level: PrrLevel.ONE,
            key: 'inappropriate_for_minors',
            categoryName: 'Inappropriate for Minors',
            category: PrrCategory.INAPPROPRIATE_FOR_MINORS,
            name: 'Piracy & Copyright Theft',
            status: UrlStatus.BLOCK,
        },
        '10081': {
            level: PrrLevel.ONE,
            key: 'inappropriate_for_minors',
            categoryName: 'Inappropriate for Minors',
            category: PrrCategory.INAPPROPRIATE_FOR_MINORS,
            name: 'School Cheating',
            status: UrlStatus.BLOCK,
        },
        '10082': {
            level: PrrLevel.THREE,
            key: 'self_harm_suicidal_content',
            category: PrrCategory.SELF_HARM_SUICIDAL_CONTENT,
            categoryName: 'Self Harm/Suicidal Content',
            name: 'Self Harm',
            status: UrlStatus.BLOCK,
        },
        '10083': {
            level: PrrLevel.ONE,
            key: 'inappropriate_for_minors',
            categoryName: 'Inappropriate for Minors',
            category: PrrCategory.INAPPROPRIATE_FOR_MINORS,
            name: 'Torrent Repository',
            status: UrlStatus.BLOCK,
        },
        '10084': {
            level: PrrLevel.ONE,
            key: 'criminal_malicious',
            category: PrrCategory.CRIMINAL_MALICIOUS,
            categoryName: 'Criminal/Malicious',
            name: 'Criminal Activities - Other',
            status: UrlStatus.BLOCK,
        },
        '10085': {
            level: PrrLevel.ONE,
            key: 'inappropriate_for_minors',
            categoryName: 'Inappropriate for Minors',
            category: PrrCategory.INAPPROPRIATE_FOR_MINORS,
            name: 'Anonymizer',
            status: UrlStatus.BLOCK,
        },
        '10086': {
            level: PrrLevel.ONE,
            key: 'social_media_chat',
            category: PrrCategory.SOCIAL_MEDIA_CHAT,
            categoryName: 'Social Media and Chat',
            name: 'Chat',
            status: UrlStatus.BLOCK,
        },
        '10087': {
            level: PrrLevel.ONE,
            key: 'social_media_chat',
            category: PrrCategory.SOCIAL_MEDIA_CHAT,
            categoryName: 'Social Media and Chat',
            name: 'Community Forums',
            status: UrlStatus.BLOCK,
        },
        '10088': {
            level: PrrLevel.ONE,
            key: 'social_media_chat',
            category: PrrCategory.SOCIAL_MEDIA_CHAT,
            categoryName: 'Social Media and Chat',
            name: 'Instant Messenger',
            status: UrlStatus.BLOCK,
        },
        '10094': {
            level: PrrLevel.ONE,
            key: 'social_media_chat',
            category: PrrCategory.SOCIAL_MEDIA_CHAT,
            categoryName: 'Social Media and Chat',
            name: 'Social Networking',
            status: UrlStatus.BLOCK,
        },
        '10095': {
            level: PrrLevel.ONE,
            key: 'social_media_chat',
            category: PrrCategory.SOCIAL_MEDIA_CHAT,
            categoryName: 'Social Media and Chat',
            name: 'Text Messaging & SMS',
            status: UrlStatus.BLOCK,
        },
        '10121': {
            level: PrrLevel.ONE,
            key: 'entertainment_news_streaming',
            categoryName: 'Entertainment News and Streaming',
            category: PrrCategory.ENTERTAINMENT_NEWS_STREAMING,
            name: 'Entertainment News & Celebrity Sites',
            status: UrlStatus.BLOCK,
        },
        '10122': {
            level: PrrLevel.ONE,
            key: 'entertainment_news_streaming',
            categoryName: 'Entertainment News and Streaming',
            category: PrrCategory.ENTERTAINMENT_NEWS_STREAMING,
            name: 'Entertainment Venues & Events',
            status: UrlStatus.BLOCK,
        },
        '10123': {
            level: PrrLevel.ONE,
            key: 'entertainment_news_streaming',
            categoryName: 'Entertainment News and Streaming',
            category: PrrCategory.ENTERTAINMENT_NEWS_STREAMING,
            name: 'Humor',
            status: UrlStatus.BLOCK,
        },
        '10124': {
            level: PrrLevel.ONE,
            key: 'entertainment_news_streaming',
            categoryName: 'Entertainment News and Streaming',
            category: PrrCategory.ENTERTAINMENT_NEWS_STREAMING,
            name: 'Movies',
            status: UrlStatus.BLOCK,
        },
        '10140': {
            level: PrrLevel.ONE,
            key: 'clothing_fashion_jewelry',
            categoryName: 'Clothing, Fashion and Jewelry',
            category: PrrCategory.CLOTHING_FASHION_JEWELRY,
            name: 'Accessories',
            status: UrlStatus.BLOCK,
        },
        '10141': {
            level: PrrLevel.ONE,
            key: 'clothing_fashion_jewelry',
            categoryName: 'Clothing, Fashion and Jewelry',
            category: PrrCategory.CLOTHING_FASHION_JEWELRY,
            name: 'Beauty',
            status: UrlStatus.BLOCK,
        },
        '10142': {
            level: PrrLevel.ONE,
            key: 'clothing_fashion_jewelry',
            categoryName: 'Clothing, Fashion and Jewelry',
            category: PrrCategory.CLOTHING_FASHION_JEWELRY,
            name: 'Body Art',
            status: UrlStatus.BLOCK,
        },
        '10143': {
            level: PrrLevel.ONE,
            key: 'clothing_fashion_jewelry',
            categoryName: 'Clothing, Fashion and Jewelry',
            category: PrrCategory.CLOTHING_FASHION_JEWELRY,
            name: 'Clothing',
            status: UrlStatus.BLOCK,
        },
        '10144': {
            level: PrrLevel.ONE,
            key: 'clothing_fashion_jewelry',
            categoryName: 'Clothing, Fashion and Jewelry',
            category: PrrCategory.CLOTHING_FASHION_JEWELRY,
            name: 'Fashion',
            status: UrlStatus.BLOCK,
        },
        '10145': {
            level: PrrLevel.ONE,
            key: 'clothing_fashion_jewelry',
            categoryName: 'Clothing, Fashion and Jewelry',
            category: PrrCategory.CLOTHING_FASHION_JEWELRY,
            name: 'Jewelry',
            status: UrlStatus.BLOCK,
        },
        '10147': {
            level: PrrLevel.ONE,
            key: 'clothing_fashion_jewelry',
            categoryName: 'Clothing, Fashion and Jewelry',
            category: PrrCategory.CLOTHING_FASHION_JEWELRY,
            name: 'Fashion - Other',
            status: UrlStatus.BLOCK,
        },
        '10168': {
            level: PrrLevel.ONE,
            key: 'drugs_alcohol_tobacco',
            category: PrrCategory.DRUGS_ALCOHOL_TOBACCO,
            categoryName: 'Drugs, Alcohol, or Tobacco Related',
            name: 'Cocktails/Beer',
            status: UrlStatus.BLOCK,
        },
        '10181': {
            level: PrrLevel.ONE,
            key: 'drugs_alcohol_tobacco',
            category: PrrCategory.DRUGS_ALCOHOL_TOBACCO,
            categoryName: 'Drugs, Alcohol, or Tobacco Related',
            name: 'Wine',
            status: UrlStatus.BLOCK,
        },
        '10198': {
            level: PrrLevel.ONE,
            key: 'body_image',
            category: PrrCategory.BODY_IMAGE,
            categoryName: 'Body Image/Related to Disordered Eating',
            name: 'Cosmetic Surgery',
            status: UrlStatus.BLOCK,
        },
        '10232': {
            level: PrrLevel.ONE,
            key: 'body_image',
            category: PrrCategory.BODY_IMAGE,
            categoryName: 'Body Image/Related to Disordered Eating',
            name: 'Weight Loss',
            status: UrlStatus.BLOCK,
        },
        '10244': {
            level: PrrLevel.ONE,
            key: 'drugs_alcohol_tobacco',
            category: PrrCategory.DRUGS_ALCOHOL_TOBACCO,
            categoryName: 'Drugs, Alcohol, or Tobacco Related',
            name: 'Cigars',
            status: UrlStatus.BLOCK,
        },
        '10266': {
            level: PrrLevel.ONE,
            key: 'online_gaming',
            categoryName: 'Online Gaming',
            category: PrrCategory.ONLINE_GAMING,
            name: 'Gaming',
            status: UrlStatus.BLOCK,
        },
        '10283': {
            level: PrrLevel.ONE,
            key: 'inappropriate_for_minors',
            categoryName: 'Inappropriate for Minors',
            category: PrrCategory.INAPPROPRIATE_FOR_MINORS,
            name: 'Dating & Relationships',
            status: UrlStatus.BLOCK,
        },
        '10292': {
            level: PrrLevel.ONE,
            key: 'criminal_malicious',
            category: PrrCategory.CRIMINAL_MALICIOUS,
            categoryName: 'Criminal/Malicious',
            name: 'Ad Fraud',
            status: UrlStatus.ALLOW,
        }, // because of green color
        '10293': {
            level: PrrLevel.ONE,
            key: 'criminal_malicious',
            category: PrrCategory.CRIMINAL_MALICIOUS,
            categoryName: 'Criminal/Malicious',
            name: 'Botnet',
            status: UrlStatus.ALLOW,
        }, // because of green color
        '10294': {
            level: PrrLevel.ONE,
            key: 'criminal_malicious',
            category: PrrCategory.CRIMINAL_MALICIOUS,
            categoryName: 'Criminal/Malicious',
            name: 'Command and Control Centers',
            status: UrlStatus.ALLOW,
        }, // because of green color
        '10295': {
            level: PrrLevel.ONE,
            key: 'criminal_malicious',
            category: PrrCategory.CRIMINAL_MALICIOUS,
            categoryName: 'Criminal/Malicious',
            name: 'Compromised & Links To Malware',
            status: UrlStatus.ALLOW,
        }, // because of green color
        '10296': {
            level: PrrLevel.ONE,
            key: 'criminal_malicious',
            category: PrrCategory.CRIMINAL_MALICIOUS,
            categoryName: 'Criminal/Malicious',
            name: 'Malware Call-Home',
            status: UrlStatus.ALLOW,
        }, // because of green color
        '10297': {
            level: PrrLevel.ONE,
            key: 'criminal_malicious',
            category: PrrCategory.CRIMINAL_MALICIOUS,
            categoryName: 'Criminal/Malicious',
            name: 'Malware Distribution Point',
            status: UrlStatus.ALLOW,
        }, // because of green color
        '10298': {
            level: PrrLevel.ONE,
            key: 'criminal_malicious',
            category: PrrCategory.CRIMINAL_MALICIOUS,
            categoryName: 'Criminal/Malicious',
            name: 'Phishing/Fraud',
            status: UrlStatus.ALLOW,
        }, // because of green color
        '10299': {
            level: PrrLevel.ONE,
            key: 'criminal_malicious',
            category: PrrCategory.CRIMINAL_MALICIOUS,
            categoryName: 'Criminal/Malicious',
            name: 'Spam URLs',
            status: UrlStatus.ALLOW,
        }, // because of green color
        '10300': {
            level: PrrLevel.ONE,
            key: 'inappropriate_for_minors',
            categoryName: 'Inappropriate for Minors',
            category: PrrCategory.INAPPROPRIATE_FOR_MINORS,
            name: 'Spyware & Questionable Software',
            status: UrlStatus.ALLOW,
        }, // because of green color
        '10315': {
            level: PrrLevel.ONE,
            key: 'inappropriate_for_minors',
            categoryName: 'Inappropriate for Minors',
            category: PrrCategory.INAPPROPRIATE_FOR_MINORS,
            name: 'Pay To Surf',
            status: UrlStatus.ALLOW,
        }, // because of green color
        // "10358":{level:1, key:"situational_awareness", categoryName:"Situational awareness", name:"Paranormal Phenomena", status:'block' },
        '10364': {
            level: PrrLevel.ONE,
            key: 'shopping_product_reviews',
            category: PrrCategory.SHOPPING_PRODUCT_REVIEWS,
            categoryName: 'Shopping and Product Reviews',
            name: 'Catalogs',
            status: UrlStatus.BLOCK,
        },
        '10365': {
            level: PrrLevel.ONE,
            key: 'inappropriate_for_minors',
            categoryName: 'Inappropriate for Minors',
            category: PrrCategory.INAPPROPRIATE_FOR_MINORS,
            name: 'Contests & Surveys',
            status: UrlStatus.BLOCK,
        },
        '10366': {
            level: PrrLevel.ONE,
            key: 'shopping_product_reviews',
            category: PrrCategory.SHOPPING_PRODUCT_REVIEWS,
            categoryName: 'Shopping and Product Reviews',
            name: 'Coupons',
            status: UrlStatus.BLOCK,
        },
        '10367': {
            level: PrrLevel.ONE,
            key: 'shopping_product_reviews',
            category: PrrCategory.SHOPPING_PRODUCT_REVIEWS,
            categoryName: 'Shopping and Product Reviews',
            name: 'Engines',
            status: UrlStatus.BLOCK,
        },
        '10368': {
            level: PrrLevel.ONE,
            key: 'shopping_product_reviews',
            category: PrrCategory.SHOPPING_PRODUCT_REVIEWS,
            categoryName: 'Shopping and Product Reviews',
            name: 'Online Shopping',
            status: UrlStatus.BLOCK,
        },
        '10369': {
            level: PrrLevel.ONE,
            key: 'shopping_product_reviews',
            category: PrrCategory.SHOPPING_PRODUCT_REVIEWS,
            categoryName: 'Shopping and Product Reviews',
            name: 'Product Reviews & Price Comparisons',
            status: UrlStatus.BLOCK,
        },
        '10370': {
            level: PrrLevel.ONE,
            key: 'shopping_product_reviews',
            category: PrrCategory.SHOPPING_PRODUCT_REVIEWS,
            categoryName: 'Shopping and Product Reviews',
            name: 'Shopping - Other',
            status: UrlStatus.BLOCK,
        },
        '10448': {
            level: PrrLevel.ONE,
            key: 'inappropriate_for_minors',
            categoryName: 'Inappropriate for Minors',
            category: PrrCategory.INAPPROPRIATE_FOR_MINORS,
            name: 'Peer-to-Peer',
            status: UrlStatus.BLOCK,
        },
        '10490': {
            level: PrrLevel.THREE,
            key: 'criminal_malicious',
            category: PrrCategory.CRIMINAL_MALICIOUS,
            categoryName: 'Criminal/Malicious',
            name: 'Terrorism',
            status: UrlStatus.BLOCK,
        },
        '10492': {
            level: PrrLevel.ONE,
            key: 'inappropriate_for_minors',
            categoryName: 'Inappropriate for Minors',
            category: PrrCategory.INAPPROPRIATE_FOR_MINORS,
            name: 'Cryptocurrency Mining',
            status: UrlStatus.BLOCK,
        },
        '10494': {
            level: PrrLevel.ONE,
            key: 'fake_news',
            categoryName: 'Fake News',
            category: PrrCategory.FAKE_NEWS,
            name: 'Fake News',
            status: UrlStatus.BLOCK,
        },
        '10280': {
            level: PrrLevel.ONE,
            key: '',
            categoryName: 'Educational',
            category: PrrCategory.EDUCATIONAL,
            name: 'Educational',
            status: UrlStatus.ALLOW,
        },
        '10106': {
            level: PrrLevel.ONE,
            key: '',
            categoryName: 'Educational',
            category: PrrCategory.EDUCATIONAL,
            name: 'Educational',
            status: UrlStatus.ALLOW,
        },
        '10313': {
            level: 0,
            key: '',
            categoryName: 'Search Engines',
            category: PrrCategory.SEARCH_ENGINES,
            name: 'WebSearch',
            status: UrlStatus.ALLOW,
        },
        '10312': {
            level: 0,
            key: '',
            categoryName: 'Portal',
            category: PrrCategory.PORTAL,
            name: 'Portal Search',
            status: UrlStatus.ALLOW,
        },
    };

    private static readonly zveloCategoricalCodes: Record<string, { categoryName: string; name: string; status: UrlStatus }> =
        ZveloCategoryCodes.CATEGORIES_CODES;

    static get() {
        return this.zveloCategoricalCodes;
    }
}
