export enum PrrUserAction {
    MESSAGE_ACTION_YES_PLEASE_CLOSE_IT="MESSAGE_ACTION_YES_PLEASE_CLOSE_IT",
    MESSAGE_ACTION_NO_LEAVE_IT_OPEN="MESSAGE_ACTION_NO_LEAVE_IT_OPEN",
    COMPOSE_ACTION_YES_ITS_FINE="COMPOSE_ACTION_YES_ITS_FINE",
    COMPOSE_ACTION_NO_TRY_AGAIN="COMPOSE_ACTION_NO_TRY_AGAIN",
    MESSAGE_ACTION_TALK_TO_ADULT="MESSAGE_ACTION_TALK_TO_ADULT",
    THREAD_ACTION_ITS_UNKIND="THREAD_ACTION_ITS_UNKIND",
    THREAD_ACTION_ITS_FINE="THREAD_ACTION_ITS_FINE",
    MESSAGE_ACTION_YES="MESSAGE_ACTION_YES",
    MESSAGE_ACTION_NO="MESSAGE_ACTION_NO",
}
