export enum AlarmType {
    SUBSCRIPTION_ALARM = 'SUBSCRIPTION_ALARM',
    CONFIGURATION_ALARM = 'CONFIGURATION_ALARM',
    CHECK_LOGIN_ALARM = 'CHECK_LOGIN_ALARM',
    EXTENSION_UPDATE_ALARM = 'EXTENSION_UPDATE_ALARM',
    PRR2_LIMIT_ALARM = 'PRR2_LIMIT_ALARM',
    INFORM_EVENT_ALARM = 'INFORM_EVENT_ALARM',
}
