export enum EmailEventTypes {
    READ_MESSAGE = 'READ_MESSAGE',
    EMAIL_THREAD_READ_EVENT = 'EMAIL_THREAD_READ_EVENT',
    EMAIL_THREAD_FLAG_EVENT = 'EMAIL_THREAD_FLAG_EVENT',
    EMAIL_READ_EVENT = 'EMAIL_READ_EVENT',
    EMAIL_MESSAGE_FLAG_EVENT = 'EMAIL_MESSAGE_FLAG_EVENT',
    EMAIL_SEND_EVENT = 'EMAIL_SEND_EVENT',
    EMAIL_READ_PRR_EVENT = 'EMAIL_READ_PRR_EVENT',
}
