import {WebCategoryTypesEnum} from "@safekids-ai/web-category-types";

const googleMapping: { [key: string]: WebCategoryTypesEnum[] } = {
  "/Adult": [WebCategoryTypesEnum.EXPLICIT],
  "/Arts & Entertainment/Events & Listings/Bars, Clubs & Nightlife": [WebCategoryTypesEnum.INAPPROPRIATE_FOR_MINORS],
  "/Arts & Entertainment/Music & Audio/Music Streams & Downloads": [WebCategoryTypesEnum.ENTERTAINMENT_STREAMING_VIDEO],
  "/Arts & Entertainment/Music & Audio/Music Videos": [WebCategoryTypesEnum.ENTERTAINMENT_STREAMING_VIDEO],
  "/Arts & Entertainment/TV & Video/Online Video": [WebCategoryTypesEnum.ENTERTAINMENT_STREAMING_VIDEO],
  "/Arts & Entertainment/TV & Video/TV Commercials": [WebCategoryTypesEnum.ENTERTAINMENT_STREAMING_VIDEO],
  "/Arts & Entertainment/TV & Video/TV Shows & Programs": [WebCategoryTypesEnum.ENTERTAINMENT_STREAMING_VIDEO],
  "/Arts & Entertainment/TV & Video/Other": [WebCategoryTypesEnum.ENTERTAINMENT_STREAMING_VIDEO],
  "/Beauty & Fitness/Beauty Pageants": [WebCategoryTypesEnum.CLOTHING_FASHION_BEAUTY],
  "/Beauty & Fitness/Other": [WebCategoryTypesEnum.CLOTHING_FASHION_BEAUTY],
  "/Beauty & Fitness/Beauty Services & Spas/Cosmetic Procedures": [WebCategoryTypesEnum.SELF_BODY_IMAGE],
  "/Beauty & Fitness/Beauty Services & Spas/Manicures & Pedicures": [WebCategoryTypesEnum.CLOTHING_FASHION_BEAUTY],
  "/Beauty & Fitness/Beauty Services & Spas/Massage Therapy": [WebCategoryTypesEnum.CLOTHING_FASHION_BEAUTY],
  "/Beauty & Fitness/Face & Body Care/Clean Beauty": [WebCategoryTypesEnum.CLOTHING_FASHION_BEAUTY],
  "/Beauty & Fitness/Face & Body Care/Make-Up & Cosmetics": [WebCategoryTypesEnum.CLOTHING_FASHION_BEAUTY],
  "/Beauty & Fitness/Face & Body Care/Perfumes & Fragrances": [WebCategoryTypesEnum.CLOTHING_FASHION_BEAUTY],
  "/Beauty & Fitness/Face & Body Care/Skin & Nail Care": [WebCategoryTypesEnum.CLOTHING_FASHION_BEAUTY],
  "/Beauty & Fitness/Face & Body Care/Sun Care & Tanning Products": [WebCategoryTypesEnum.CLOTHING_FASHION_BEAUTY],
  "/Beauty & Fitness/Face & Body Care/Unwanted Body & Facial Hair Removal": [WebCategoryTypesEnum.CLOTHING_FASHION_BEAUTY],
  "/Beauty & Fitness/Fashion & Style/Fashion Designers & Collections": [WebCategoryTypesEnum.CLOTHING_FASHION_BEAUTY],
  "/Beauty & Fitness/Hair Care/Hair Loss": [WebCategoryTypesEnum.CLOTHING_FASHION_BEAUTY],
  "/Beauty & Fitness/Hair Care/Shampoos & Conditioners": [WebCategoryTypesEnum.CLOTHING_FASHION_BEAUTY],
  "/Computers & Electronics/Computer Security/Antivirus & Malware": [WebCategoryTypesEnum.PHISHING_FRAUD],
  "/Computers & Electronics/Computer Security/Hacking & Cracking": [WebCategoryTypesEnum.PHISHING_FRAUD],
  "/Computers & Electronics/Networking/VPN & Remote Access": [WebCategoryTypesEnum.PROXY_VPN],
  "/Food & Drink/Beverages/Alcoholic Beverages": [WebCategoryTypesEnum.DRUGS_ALCOHOL],
  "/Games/Arcade & Coin-Op Games": [WebCategoryTypesEnum.ONLINE_GAMES],
  "/Games/Other": [WebCategoryTypesEnum.ONLINE_GAMES],
  "/Games/Card Games/Poker & Casino Games": [WebCategoryTypesEnum.GAMBLING, WebCategoryTypesEnum.ONLINE_GAMES],
  "/Games/Computer & Video Games/Fighting Games": [WebCategoryTypesEnum.ONLINE_GAMES, WebCategoryTypesEnum.INAPPROPRIATE_FOR_MINORS],
  "/Games/Computer & Video Games/Shooter Games": [WebCategoryTypesEnum.ONLINE_GAMES, WebCategoryTypesEnum.INAPPROPRIATE_FOR_MINORS],
  "/Health/Health Conditions/Eating Disorders": [WebCategoryTypesEnum.SELF_BODY_IMAGE],
  "/Health/Reproductive Health/Sex Education & Counseling": [WebCategoryTypesEnum.SEX_EDUCATION],
  "/Sensitive Subjects/Accidents & Disasters": [WebCategoryTypesEnum.VIOLENCE],
  "/Sensitive Subjects/Death & Tragedy": [WebCategoryTypesEnum.VIOLENCE],
  "/Sensitive Subjects/Firearms & Weapons": [WebCategoryTypesEnum.VIOLENCE],
  "/Sensitive Subjects/Recreational Drugs": [WebCategoryTypesEnum.DRUGS_ALCOHOL],
  "/Sensitive Subjects/Self-Harm": [WebCategoryTypesEnum.SELF_HARM],
  "/Sensitive Subjects/Violence & Abuse": [WebCategoryTypesEnum.VIOLENCE],
  "/Sensitive Subjects/War & Conflict": [WebCategoryTypesEnum.VIOLENCE],
  "/Shopping/Shopping Portals": [WebCategoryTypesEnum.SHOPPING_PRODUCT_REVIEWS],
  "/Shopping/Apparel/Apparel Services": [WebCategoryTypesEnum.SHOPPING_PRODUCT_REVIEWS, WebCategoryTypesEnum.CLOTHING_FASHION_BEAUTY],
  "/Shopping/Apparel/Athletic Apparel": [WebCategoryTypesEnum.SHOPPING_PRODUCT_REVIEWS, WebCategoryTypesEnum.CLOTHING_FASHION_BEAUTY],
  "/Shopping/Apparel/Casual Apparel": [WebCategoryTypesEnum.SHOPPING_PRODUCT_REVIEWS, WebCategoryTypesEnum.CLOTHING_FASHION_BEAUTY],
  "/Shopping/Apparel/Children's Clothing": [WebCategoryTypesEnum.SHOPPING_PRODUCT_REVIEWS, WebCategoryTypesEnum.CLOTHING_FASHION_BEAUTY],
  "/Shopping/Apparel/Clothing Accessories": [WebCategoryTypesEnum.SHOPPING_PRODUCT_REVIEWS, WebCategoryTypesEnum.CLOTHING_FASHION_BEAUTY],
  "/Shopping/Apparel/Costumes": [WebCategoryTypesEnum.SHOPPING_PRODUCT_REVIEWS, WebCategoryTypesEnum.CLOTHING_FASHION_BEAUTY],
  "/Shopping/Apparel/Eyewear": [WebCategoryTypesEnum.SHOPPING_PRODUCT_REVIEWS, WebCategoryTypesEnum.CLOTHING_FASHION_BEAUTY],
  "/Shopping/Apparel/Footwear": [WebCategoryTypesEnum.SHOPPING_PRODUCT_REVIEWS, WebCategoryTypesEnum.CLOTHING_FASHION_BEAUTY],
  "/Shopping/Apparel/Formal Wear": [WebCategoryTypesEnum.SHOPPING_PRODUCT_REVIEWS, WebCategoryTypesEnum.CLOTHING_FASHION_BEAUTY],
  "/Shopping/Apparel/Headwear": [WebCategoryTypesEnum.SHOPPING_PRODUCT_REVIEWS, WebCategoryTypesEnum.CLOTHING_FASHION_BEAUTY],
  "/Shopping/Apparel/Men's Clothing": [WebCategoryTypesEnum.SHOPPING_PRODUCT_REVIEWS, WebCategoryTypesEnum.CLOTHING_FASHION_BEAUTY],
  "/Shopping/Apparel/Outerwear": [WebCategoryTypesEnum.SHOPPING_PRODUCT_REVIEWS, WebCategoryTypesEnum.CLOTHING_FASHION_BEAUTY],
  "/Shopping/Apparel/Pants & Shorts": [WebCategoryTypesEnum.SHOPPING_PRODUCT_REVIEWS, WebCategoryTypesEnum.CLOTHING_FASHION_BEAUTY],
  "/Shopping/Apparel/Shirts & Tops": [WebCategoryTypesEnum.SHOPPING_PRODUCT_REVIEWS, WebCategoryTypesEnum.CLOTHING_FASHION_BEAUTY],
  "/Shopping/Apparel/Sleepwear": [WebCategoryTypesEnum.SHOPPING_PRODUCT_REVIEWS, WebCategoryTypesEnum.CLOTHING_FASHION_BEAUTY],
  "/Shopping/Apparel/Suits & Business Attire": [WebCategoryTypesEnum.SHOPPING_PRODUCT_REVIEWS, WebCategoryTypesEnum.CLOTHING_FASHION_BEAUTY],
  "/Shopping/Apparel/Swimwear": [WebCategoryTypesEnum.SHOPPING_PRODUCT_REVIEWS, WebCategoryTypesEnum.CLOTHING_FASHION_BEAUTY],
  "/Shopping/Apparel/Undergarments": [WebCategoryTypesEnum.SHOPPING_PRODUCT_REVIEWS, WebCategoryTypesEnum.CLOTHING_FASHION_BEAUTY],
  "/Shopping/Apparel/Uniforms & Workwear": [WebCategoryTypesEnum.SHOPPING_PRODUCT_REVIEWS],
  "/Shopping/Apparel/Women's Clothing": [WebCategoryTypesEnum.SHOPPING_PRODUCT_REVIEWS, WebCategoryTypesEnum.CLOTHING_FASHION_BEAUTY],
  "/Shopping/Apparel/Other": [WebCategoryTypesEnum.SHOPPING_PRODUCT_REVIEWS, WebCategoryTypesEnum.CLOTHING_FASHION_BEAUTY],
  "/Shopping/Discount & Outlet Stores": [WebCategoryTypesEnum.SHOPPING_PRODUCT_REVIEWS],
  "/Shopping/Tobacco & Vaping Products": [WebCategoryTypesEnum.DRUGS_ALCOHOL, WebCategoryTypesEnum.SHOPPING_PRODUCT_REVIEWS],
  "/Internet & Telecom/Email & Messaging/Electronic Spam": [WebCategoryTypesEnum.PHISHING_FRAUD],
  "/Internet & Telecom/Email & Messaging/Text & Instant Messaging": [WebCategoryTypesEnum.SOCIAL_MEDIA_CHAT],
  "/Internet & Telecom/Email & Messaging/Voice & Video Chat": [WebCategoryTypesEnum.SOCIAL_MEDIA_CHAT],
  "/Online Communities/Dating & Personals/Other": [WebCategoryTypesEnum.INAPPROPRIATE_FOR_MINORS],
  "/Online Communities/Dating & Personals/Matrimonial Services": [WebCategoryTypesEnum.INAPPROPRIATE_FOR_MINORS],
  "/Online Communities/Dating & Personals/Personals": [WebCategoryTypesEnum.INAPPROPRIATE_FOR_MINORS],
  "/Online Communities/Dating & Personals/Photo Rating Sites": [WebCategoryTypesEnum.INAPPROPRIATE_FOR_MINORS],
  "/Online Communities/File Sharing & Hosting": [WebCategoryTypesEnum.INAPPROPRIATE_FOR_MINORS],
  "/Online Communities/Online Goodies/Social Network Apps & Add-Ons": [WebCategoryTypesEnum.SOCIAL_MEDIA_CHAT],
  "/Online Communities/Photo & Video Sharing/Photo & Image Sharing": [WebCategoryTypesEnum.SOCIAL_MEDIA_CHAT],
  "/Online Communities/Photo & Video Sharing/Video Sharing": [WebCategoryTypesEnum.SOCIAL_MEDIA_CHAT],
  "/Online Communities/Other": [WebCategoryTypesEnum.SOCIAL_MEDIA_CHAT],
  "/Online Communities/Social Networks": [WebCategoryTypesEnum.SOCIAL_MEDIA_CHAT],
  "/Online Communities/Virtual Worlds": [WebCategoryTypesEnum.INAPPROPRIATE_FOR_MINORS]
};

export {googleMapping}
