export type WebCategoryType = {
  id: number,
  description: string
}

export const SAFE_KIDS_CATEGORY_TYPES: WebCategoryType[] = [
  {"id": 1, "description": "Adult Sexual Content"},
  {"id": 2, "description": "Body Image/Related to Eating Disorder"},
  {"id": 3, "description": "Criminal/Malicious"},
  {"id": 4, "description": "Drugs/Alchohol/Tobacco Related"},
  {"id": 5, "description": "Fake News"},
  {"id": 6, "description": "Gambling"},
  {"id": 7, "description": "Hate Speech"},
  {"id": 8, "description": "Inappropriate for Minors"},
  {"id": 9, "description": "Self Harm/Suicidal Content"},
  {"id": 10, "description": "Violence"},
  {"id": 11, "description": "Weapon"},
  {"id": 12, "description": "Other"},
]
export const DETAIL_WEB_CATEGORY_TYPES: WebCategoryType[] = [
  {"id": 1, "description": "Adult"},
  {"id": 2, "description": "/Arts & Entertainment"},
  {"id": 3, "description": "/Arts & Entertainment/Celebrities & Entertainment News"},
  {"id": 4, "description": "/Arts & Entertainment/Comics & Animation"},
  {"id": 5, "description": "/Arts & Entertainment/Comics & Animation/Anime & Manga"},
  {"id": 6, "description": "/Arts & Entertainment/Comics & Animation/Cartoons"},
  {"id": 7, "description": "/Arts & Entertainment/Comics & Animation/Comics"},
  {"id": 8, "description": "/Arts & Entertainment/Entertainment Industry"},
  {"id": 9, "description": "/Arts & Entertainment/Entertainment Industry/Film & TV Industry"},
  {"id": 10, "description": "/Arts & Entertainment/Entertainment Industry/Recording Industry"},
  {"id": 11, "description": "/Arts & Entertainment/Events & Listings"},
  {"id": 12, "description": "/Arts & Entertainment/Events & Listings/Bars, Clubs & Nightlife"},
  {"id": 13, "description": "/Arts & Entertainment/Events & Listings/Concerts & Music Festivals"},
  {"id": 14, "description": "/Arts & Entertainment/Events & Listings/Expos & Conventions"},
  {"id": 15, "description": "/Arts & Entertainment/Events & Listings/Film Festivals"},
  {"id": 16, "description": "/Arts & Entertainment/Events & Listings/Movie Listings & Theater Showtimes"},
  {"id": 17, "description": "/Arts & Entertainment/Fun & Trivia"},
  {"id": 18, "description": "/Arts & Entertainment/Fun & Trivia/Flash-Based Entertainment"},
  {"id": 19, "description": "/Arts & Entertainment/Fun & Trivia/Fun Tests & Silly Surveys"},
  {"id": 20, "description": "/Arts & Entertainment/Humor"},
  {"id": 21, "description": "/Arts & Entertainment/Humor/Funny Pictures & Videos"},
  {"id": 22, "description": "/Arts & Entertainment/Humor/Political Humor"},
  {"id": 23, "description": "/Arts & Entertainment/Movies"},
  {"id": 24, "description": "/Arts & Entertainment/Music & Audio"},
  {"id": 25, "description": "/Arts & Entertainment/Music & Audio/CD & Audio Shopping"},
  {"id": 26, "description": "/Arts & Entertainment/Music & Audio/Classical Music"},
  {"id": 27, "description": "/Arts & Entertainment/Music & Audio/Country Music"},
  {"id": 28, "description": "/Arts & Entertainment/Music & Audio/Dance & Electronic Music"},
  {"id": 29, "description": "/Arts & Entertainment/Music & Audio/Experimental & Industrial Music"},
  {"id": 30, "description": "/Arts & Entertainment/Music & Audio/Jazz & Blues"},
  {"id": 31, "description": "/Arts & Entertainment/Music & Audio/Music Education & Instruction"},
  {"id": 32, "description": "/Arts & Entertainment/Music & Audio/Music Equipment & Technology"},
  {"id": 33, "description": "/Arts & Entertainment/Music & Audio/Music Reference"},
  {"id": 34, "description": "/Arts & Entertainment/Music & Audio/Music Streams & Downloads"},
  {"id": 35, "description": "/Arts & Entertainment/Music & Audio/Music Videos"},
  {"id": 36, "description": "/Arts & Entertainment/Music & Audio/Pop Music"},
  {"id": 37, "description": "/Arts & Entertainment/Music & Audio/Radio"},
  {"id": 38, "description": "/Arts & Entertainment/Music & Audio/Religious Music"},
  {"id": 39, "description": "/Arts & Entertainment/Music & Audio/Rock Music"},
  {"id": 40, "description": "/Arts & Entertainment/Music & Audio/Soundtracks"},
  {"id": 41, "description": "/Arts & Entertainment/Music & Audio/Urban & Hip-Hop"},
  {"id": 42, "description": "/Arts & Entertainment/Music & Audio/World Music"},
  {"id": 43, "description": "/Arts & Entertainment/Offbeat"},
  {"id": 44, "description": "/Arts & Entertainment/Offbeat/Occult & Paranormal"},
  {"id": 45, "description": "/Arts & Entertainment/Online Media"},
  {"id": 46, "description": "/Arts & Entertainment/Online Media/Online Image Galleries"},
  {"id": 47, "description": "/Arts & Entertainment/Performing Arts"},
  {"id": 48, "description": "/Arts & Entertainment/Performing Arts/Acting & Theater"},
  {"id": 49, "description": "/Arts & Entertainment/Performing Arts/Circus"},
  {"id": 50, "description": "/Arts & Entertainment/Performing Arts/Dance"},
  {"id": 51, "description": "/Arts & Entertainment/Performing Arts/Magic"},
  {"id": 52, "description": "/Arts & Entertainment/Performing Arts/Opera"},
  {"id": 53, "description": "/Arts & Entertainment/TV & Video"},
  {"id": 54, "description": "/Arts & Entertainment/TV & Video/Online Video"},
  {"id": 55, "description": "/Arts & Entertainment/TV & Video/TV Commercials"},
  {"id": 56, "description": "/Arts & Entertainment/TV & Video/TV Shows & Programs"},
  {"id": 57, "description": "/Arts & Entertainment/Visual Art & Design"},
  {"id": 58, "description": "/Arts & Entertainment/Visual Art & Design/Architecture"},
  {"id": 59, "description": "/Arts & Entertainment/Visual Art & Design/Art Museums & Galleries"},
  {"id": 60, "description": "/Arts & Entertainment/Visual Art & Design/Design"},
  {"id": 61, "description": "/Arts & Entertainment/Visual Art & Design/Painting"},
  {"id": 62, "description": "/Arts & Entertainment/Visual Art & Design/Photographic & Digital Arts"},
  {"id": 63, "description": "/Autos & Vehicles"},
  {"id": 64, "description": "/Autos & Vehicles/Bicycles & Accessories"},
  {"id": 65, "description": "/Autos & Vehicles/Bicycles & Accessories/Bike Parts & Repair"},
  {"id": 66, "description": "/Autos & Vehicles/Bicycles & Accessories/BMX Bikes"},
  {"id": 67, "description": "/Autos & Vehicles/Boats & Watercraft"},
  {"id": 68, "description": "/Autos & Vehicles/Campers & RVs"},
  {"id": 69, "description": "/Autos & Vehicles/Classic Vehicles"},
  {"id": 70, "description": "/Autos & Vehicles/Commercial Vehicles/Cargo Trucks & Trailers"},
  {"id": 71, "description": "/Autos & Vehicles/Motor Vehicles (By Type)"},
  {"id": 72, "description": "/Autos & Vehicles/Motor Vehicles (By Type)/Hybrid & Alternative Vehicles"},
  {"id": 73, "description": "/Autos & Vehicles/Motor Vehicles (By Type)/Motorcycles"},
  {"id": 74, "description": "/Autos & Vehicles/Motor Vehicles (By Type)/Off-Road Vehicles"},
  {"id": 75, "description": "/Autos & Vehicles/Motor Vehicles (By Type)/Trucks & SUVs"},
  {"id": 76, "description": "/Autos & Vehicles/Vehicle Codes & Driving Laws"},
  {"id": 77, "description": "/Autos & Vehicles/Vehicle Codes & Driving Laws/Vehicle Licensing & Registration"},
  {"id": 78, "description": "/Autos & Vehicles/Vehicle Parts & Services"},
  {"id": 79, "description": "/Autos & Vehicles/Vehicle Parts & Services/Gas Prices & Vehicle Fueling"},
  {"id": 80, "description": "/Autos & Vehicles/Vehicle Parts & Services/Vehicle Parts & Accessories"},
  {"id": 81, "description": "/Autos & Vehicles/Vehicle Parts & Services/Vehicle Repair & Maintenance"},
  {"id": 82, "description": "/Autos & Vehicles/Vehicle Shopping"},
  {"id": 83, "description": "/Autos & Vehicles/Vehicle Shopping/Used Vehicles"},
  {"id": 84, "description": "/Autos & Vehicles/Vehicle Shows"},
  {"id": 85, "description": "/Beauty & Fitness"},
  {"id": 86, "description": "/Beauty & Fitness/Beauty Pageants"},
  {"id": 87, "description": "/Beauty & Fitness/Body Art"},
  {"id": 88, "description": "/Beauty & Fitness/Cosmetic Procedures"},
  {"id": 89, "description": "/Beauty & Fitness/Cosmetic Procedures/Cosmetic Surgery"},
  {"id": 90, "description": "/Beauty & Fitness/Cosmetology & Beauty Professionals"},
  {"id": 91, "description": "/Beauty & Fitness/Face & Body Care"},
  {"id": 92, "description": "/Beauty & Fitness/Face & Body Care/Hygiene & Toiletries"},
  {"id": 93, "description": "/Beauty & Fitness/Face & Body Care/Make-Up & Cosmetics"},
  {"id": 94, "description": "/Beauty & Fitness/Face & Body Care/Perfumes & Fragrances"},
  {"id": 95, "description": "/Beauty & Fitness/Face & Body Care/Skin & Nail Care"},
  {"id": 96, "description": "/Beauty & Fitness/Face & Body Care/Unwanted Body & Facial Hair Removal"},
  {"id": 97, "description": "/Beauty & Fitness/Fashion & Style"},
  {"id": 98, "description": "/Beauty & Fitness/Fashion & Style/Fashion Designers & Collections"},
  {"id": 99, "description": "/Beauty & Fitness/Fitness"},
  {"id": 100, "description": "/Beauty & Fitness/Hair Care"},
  {"id": 101, "description": "/Beauty & Fitness/Hair Care/Hair Loss"},
  {"id": 102, "description": "/Beauty & Fitness/Spas & Beauty Services"},
  {"id": 103, "description": "/Beauty & Fitness/Spas & Beauty Services/Massage Therapy"},
  {"id": 104, "description": "/Beauty & Fitness/Weight Loss"},
  {"id": 105, "description": "/Books & Literature"},
  {"id": 106, "description": "/Books & Literature/Children's Literature"},
  {"id": 107, "description": "/Books & Literature/E-Books"},
  {"id": 108, "description": "/Books & Literature/Fan Fiction"},
  {"id": 109, "description": "/Books & Literature/Literary Classics"},
  {"id": 110, "description": "/Books & Literature/Poetry"},
  {"id": 111, "description": "/Books & Literature/Writers Resources"},
  {"id": 112, "description": "/Business & Industrial"},
  {"id": 113, "description": "/Business & Industrial/Advertising & Marketing/Public Relations"},
  {"id": 114, "description": "/Business & Industrial/Aerospace & Defense/Space Technology"},
  {"id": 115, "description": "/Business & Industrial/Agriculture & Forestry"},
  {"id": 116, "description": "/Business & Industrial/Agriculture & Forestry/Agricultural Equipment"},
  {"id": 117, "description": "/Business & Industrial/Agriculture & Forestry/Forestry"},
  {"id": 118, "description": "/Business & Industrial/Agriculture & Forestry/Livestock"},
  {"id": 119, "description": "/Business & Industrial/Automotive Industry"},
  {"id": 120, "description": "/Business & Industrial/Business Education"},
  {"id": 121, "description": "/Business & Industrial/Business Finance"},
  {"id": 122, "description": "/Business & Industrial/Business Finance/Venture Capital"},
  {"id": 123, "description": "/Business & Industrial/Business Operations"},
  {"id": 124, "description": "/Business & Industrial/Business Operations/Business Plans & Presentations"},
  {"id": 125, "description": "/Business & Industrial/Business Operations/Management"},
  {"id": 126, "description": "/Business & Industrial/Business Services"},
  {"id": 127, "description": "/Business & Industrial/Business Services/Consulting"},
  {"id": 128, "description": "/Business & Industrial/Business Services/Corporate Events"},
  {"id": 129, "description": "/Business & Industrial/Business Services/E-Commerce Services"},
  {"id": 130, "description": "/Business & Industrial/Business Services/Fire & Security Services"},
  {"id": 131, "description": "/Business & Industrial/Business Services/Office Services"},
  {"id": 132, "description": "/Business & Industrial/Business Services/Office Supplies"},
  {"id": 133, "description": "/Business & Industrial/Business Services/Writing & Editing Services"},
  {"id": 134, "description": "/Business & Industrial/Chemicals Industry"},
  {"id": 135, "description": "/Business & Industrial/Chemicals Industry/Cleaning Agents"},
  {"id": 136, "description": "/Business & Industrial/Chemicals Industry/Plastics & Polymers"},
  {"id": 137, "description": "/Business & Industrial/Construction & Maintenance"},
  {"id": 138, "description": "/Business & Industrial/Construction & Maintenance/Building Materials & Supplies"},
  {"id": 139, "description": "/Business & Industrial/Energy & Utilities"},
  {"id": 140, "description": "/Business & Industrial/Energy & Utilities/Electricity"},
  {"id": 141, "description": "/Business & Industrial/Energy & Utilities/Oil & Gas"},
  {"id": 142, "description": "/Business & Industrial/Energy & Utilities/Renewable & Alternative Energy"},
  {"id": 143, "description": "/Business & Industrial/Hospitality Industry"},
  {"id": 144, "description": "/Business & Industrial/Hospitality Industry/Event Planning"},
  {"id": 145, "description": "/Business & Industrial/Hospitality Industry/Food Service"},
  {"id": 146, "description": "/Business & Industrial/Industrial Materials & Equipment"},
  {"id": 147, "description": "/Business & Industrial/Industrial Materials & Equipment/Heavy Machinery"},
  {"id": 148, "description": "/Business & Industrial/Manufacturing"},
  {"id": 149, "description": "/Business & Industrial/Metals & Mining"},
  {"id": 150, "description": "/Business & Industrial/Metals & Mining/Precious Metals"},
  {"id": 151, "description": "/Business & Industrial/Pharmaceuticals & Biotech"},
  {"id": 152, "description": "/Business & Industrial/Printing & Publishing"},
  {"id": 153, "description": "/Business & Industrial/Retail Trade"},
  {"id": 154, "description": "/Business & Industrial/Retail Trade/Retail Equipment & Technology"},
  {"id": 155, "description": "/Business & Industrial/Small Business/MLM & Business Opportunities"},
  {"id": 156, "description": "/Business & Industrial/Textiles & Nonwovens"},
  {"id": 157, "description": "/Business & Industrial/Transportation & Logistics"},
  {"id": 158, "description": "/Business & Industrial/Transportation & Logistics/Freight & Trucking"},
  {"id": 159, "description": "/Business & Industrial/Transportation & Logistics/Mail & Package Delivery"},
  {"id": 160, "description": "/Business & Industrial/Transportation & Logistics/Maritime Transport"},
  {"id": 161, "description": "/Business & Industrial/Transportation & Logistics/Moving & Relocation"},
  {"id": 162, "description": "/Business & Industrial/Transportation & Logistics/Packaging"},
  {"id": 163, "description": "/Business & Industrial/Transportation & Logistics/Parking"},
  {"id": 164, "description": "/Business & Industrial/Transportation & Logistics/Rail Transport"},
  {"id": 165, "description": "/Business & Industrial/Transportation & Logistics/Urban Transport"},
  {"id": 166, "description": "/Computers & Electronics"},
  {"id": 167, "description": "/Computers & Electronics/CAD & CAM"},
  {"id": 168, "description": "/Computers & Electronics/Computer Hardware"},
  {"id": 169, "description": "/Computers & Electronics/Computer Hardware/Computer Components"},
  {"id": 170, "description": "/Computers & Electronics/Computer Hardware/Computer Drives & Storage"},
  {"id": 171, "description": "/Computers & Electronics/Computer Hardware/Computer Peripherals"},
  {"id": 172, "description": "/Computers & Electronics/Computer Hardware/Desktop Computers"},
  {"id": 173, "description": "/Computers & Electronics/Computer Hardware/Laptops & Notebooks"},
  {"id": 174, "description": "/Computers & Electronics/Computer Security"},
  {"id": 175, "description": "/Computers & Electronics/Computer Security/Hacking & Cracking"},
  {"id": 176, "description": "/Computers & Electronics/Consumer Electronics"},
  {"id": 177, "description": "/Computers & Electronics/Consumer Electronics/Audio Equipment"},
  {"id": 178, "description": "/Computers & Electronics/Consumer Electronics/Camera & Photo Equipment"},
  {"id": 179, "description": "/Computers & Electronics/Consumer Electronics/Car Electronics"},
  {"id": 180, "description": "/Computers & Electronics/Consumer Electronics/Drones & RC Aircraft"},
  {"id": 181, "description": "/Computers & Electronics/Consumer Electronics/Game Systems & Consoles"},
  {"id": 182, "description": "/Computers & Electronics/Consumer Electronics/GPS & Navigation"},
  {"id": 183, "description": "/Computers & Electronics/Consumer Electronics/TV & Video Equipment"},
  {"id": 184, "description": "/Computers & Electronics/Electronics & Electrical"},
  {"id": 185, "description": "/Computers & Electronics/Electronics & Electrical/Electronic Components"},
  {"id": 186, "description": "/Computers & Electronics/Electronics & Electrical/Power Supplies"},
  {"id": 187, "description": "/Computers & Electronics/Enterprise Technology"},
  {"id": 188, "description": "/Computers & Electronics/Enterprise Technology/Data Management"},
  {"id": 189, "description": "/Computers & Electronics/Networking"},
  {"id": 190, "description": "/Computers & Electronics/Networking/Data Formats & Protocols"},
  {"id": 191, "description": "/Computers & Electronics/Networking/Network Monitoring & Management"},
  {"id": 192, "description": "/Computers & Electronics/Networking/VPN & Remote Access"},
  {"id": 193, "description": "/Computers & Electronics/Programming"},
  {"id": 194, "description": "/Computers & Electronics/Programming/Java (Programming Language)"},
  {"id": 195, "description": "/Computers & Electronics/Software"},
  {"id": 196, "description": "/Computers & Electronics/Software/Business & Productivity Software"},
  {"id": 197, "description": "/Computers & Electronics/Software/Device Drivers"},
  {"id": 198, "description": "/Computers & Electronics/Software/Internet Software"},
  {"id": 199, "description": "/Computers & Electronics/Software/Multimedia Software"},
  {"id": 200, "description": "/Computers & Electronics/Software/Operating Systems"},
  {"id": 201, "description": "/Computers & Electronics/Software/Software Utilities"},
  {"id": 202, "description": "/Finance"},
  {"id": 203, "description": "/Finance/Accounting & Auditing"},
  {"id": 204, "description": "/Finance/Accounting & Auditing/Billing & Invoicing"},
  {"id": 205, "description": "/Finance/Accounting & Auditing/Tax Preparation & Planning"},
  {"id": 206, "description": "/Finance/Banking"},
  {"id": 207, "description": "/Finance/Credit & Lending"},
  {"id": 208, "description": "/Finance/Credit & Lending/Credit Cards"},
  {"id": 209, "description": "/Finance/Credit & Lending/Credit Reporting & Monitoring"},
  {"id": 210, "description": "/Finance/Credit & Lending/Loans"},
  {"id": 211, "description": "/Finance/Financial Planning & Management"},
  {"id": 212, "description": "/Finance/Financial Planning & Management/Retirement & Pension"},
  {"id": 213, "description": "/Finance/Grants, Scholarships & Financial Aid"},
  {"id": 214, "description": "/Finance/Grants, Scholarships & Financial Aid/Study Grants & Scholarships"},
  {"id": 215, "description": "/Finance/Insurance"},
  {"id": 216, "description": "/Finance/Insurance/Health Insurance"},
  {"id": 217, "description": "/Finance/Investing"},
  {"id": 218, "description": "/Finance/Investing/Commodities & Futures Trading"},
  {"id": 219, "description": "/Finance/Investing/Currencies & Foreign Exchange"},
  {"id": 220, "description": "/Finance/Investing/Stocks & Bonds"},
  {"id": 221, "description": "/Food & Drink"},
  {"id": 222, "description": "/Food & Drink/Beverages"},
  {"id": 223, "description": "/Food & Drink/Beverages/Alcoholic Beverages"},
  {"id": 224, "description": "/Food & Drink/Beverages/Coffee & Tea"},
  {"id": 225, "description": "/Food & Drink/Beverages/Juice"},
  {"id": 226, "description": "/Food & Drink/Beverages/Soft Drinks"},
  {"id": 227, "description": "/Food & Drink/Cooking & Recipes"},
  {"id": 228, "description": "/Food & Drink/Cooking & Recipes/BBQ & Grilling"},
  {"id": 229, "description": "/Food & Drink/Cooking & Recipes/Desserts"},
  {"id": 230, "description": "/Food & Drink/Cooking & Recipes/Soups & Stews"},
  {"id": 231, "description": "/Food & Drink/Food"},
  {"id": 232, "description": "/Food & Drink/Food & Grocery Retailers"},
  {"id": 233, "description": "/Food & Drink/Food/Baked Goods"},
  {"id": 234, "description": "/Food & Drink/Food/Breakfast Foods"},
  {"id": 235, "description": "/Food & Drink/Food/Candy & Sweets"},
  {"id": 236, "description": "/Food & Drink/Food/Grains & Pasta"},
  {"id": 237, "description": "/Food & Drink/Food/Meat & Seafood"},
  {"id": 238, "description": "/Food & Drink/Food/Snack Foods"},
  {"id": 239, "description": "/Food & Drink/Restaurants"},
  {"id": 240, "description": "/Food & Drink/Restaurants/Fast Food"},
  {"id": 241, "description": "/Food & Drink/Restaurants/Pizzerias"},
  {"id": 242, "description": "/Food & Drink/Restaurants/Restaurant Reviews & Reservations"},
  {"id": 243, "description": "/Games"},
  {"id": 244, "description": "/Games/Arcade & Coin-Op Games"},
  {"id": 245, "description": "/Games/Board Games"},
  {"id": 246, "description": "/Games/Board Games/Chess & Abstract Strategy Games"},
  {"id": 247, "description": "/Games/Board Games/Miniatures & Wargaming"},
  {"id": 248, "description": "/Games/Card Games"},
  {"id": 249, "description": "/Games/Card Games/Collectible Card Games"},
  {"id": 250, "description": "/Games/Card Games/Poker & Casino Games"},
  {"id": 251, "description": "/Games/Computer & Video Games"},
  {"id": 252, "description": "/Games/Computer & Video Games/Casual Games"},
  {"id": 253, "description": "/Games/Computer & Video Games/Driving & Racing Games"},
  {"id": 254, "description": "/Games/Computer & Video Games/Fighting Games"},
  {"id": 255, "description": "/Games/Computer & Video Games/Music & Dance Games"},
  {"id": 256, "description": "/Games/Computer & Video Games/Sandbox Games"},
  {"id": 257, "description": "/Games/Computer & Video Games/Shooter Games"},
  {"id": 258, "description": "/Games/Computer & Video Games/Simulation Games"},
  {"id": 259, "description": "/Games/Computer & Video Games/Sports Games"},
  {"id": 260, "description": "/Games/Computer & Video Games/Strategy Games"},
  {"id": 261, "description": "/Games/Computer & Video Games/Video Game Emulation"},
  {"id": 262, "description": "/Games/Family-Oriented Games & Activities"},
  {"id": 263, "description": "/Games/Family-Oriented Games & Activities/Drawing & Coloring"},
  {"id": 264, "description": "/Games/Family-Oriented Games & Activities/Dress-Up & Fashion Games"},
  {"id": 265, "description": "/Games/Gambling"},
  {"id": 266, "description": "/Games/Gambling/Lottery"},
  {"id": 267, "description": "/Games/Online Games/Massively Multiplayer Games"},
  {"id": 268, "description": "/Games/Puzzles & Brainteasers"},
  {"id": 269, "description": "/Games/Roleplaying Games"},
  {"id": 270, "description": "/Games/Table Games"},
  {"id": 271, "description": "/Games/Table Games/Billiards"},
  {"id": 272, "description": "/Games/Word Games"},
  {"id": 273, "description": "/Health"},
  {"id": 274, "description": "/Health/Aging & Geriatrics"},
  {"id": 275, "description": "/Health/Health Conditions"},
  {"id": 276, "description": "/Health/Health Conditions/AIDS & HIV"},
  {"id": 277, "description": "/Health/Health Conditions/Allergies"},
  {"id": 278, "description": "/Health/Health Conditions/Arthritis"},
  {"id": 279, "description": "/Health/Health Conditions/Cancer"},
  {"id": 280, "description": "/Health/Health Conditions/Diabetes"},
  {"id": 281, "description": "/Health/Health Conditions/Ear Nose & Throat"},
  {"id": 282, "description": "/Health/Health Conditions/Eating Disorders"},
  {"id": 283, "description": "/Health/Health Conditions/Endocrine Conditions"},
  {"id": 284, "description": "/Health/Health Conditions/Genetic Disorders"},
  {"id": 285, "description": "/Health/Health Conditions/Heart & Hypertension"},
  {"id": 286, "description": "/Health/Health Conditions/Infectious Diseases"},
  {"id": 287, "description": "/Health/Health Conditions/Neurological Conditions"},
  {"id": 288, "description": "/Health/Health Conditions/Obesity"},
  {"id": 289, "description": "/Health/Health Conditions/Pain Management"},
  {"id": 290, "description": "/Health/Health Conditions/Respiratory Conditions"},
  {"id": 291, "description": "/Health/Health Conditions/Skin Conditions"},
  {"id": 292, "description": "/Health/Health Conditions/Sleep Disorders"},
  {"id": 293, "description": "/Health/Health Education & Medical Training"},
  {"id": 294, "description": "/Health/Health Foundations & Medical Research"},
  {"id": 295, "description": "/Health/Medical Devices & Equipment"},
  {"id": 296, "description": "/Health/Medical Facilities & Services"},
  {"id": 297, "description": "/Health/Medical Facilities & Services/Doctors' Offices"},
  {"id": 298, "description": "/Health/Medical Facilities & Services/Hospitals & Treatment Centers"},
  {"id": 299, "description": "/Health/Medical Facilities & Services/Medical Procedures"},
  {"id": 300, "description": "/Health/Medical Facilities & Services/Physical Therapy"},
  {"id": 301, "description": "/Health/Men's Health"},
  {"id": 302, "description": "/Health/Mental Health"},
  {"id": 303, "description": "/Health/Mental Health/Anxiety & Stress"},
  {"id": 304, "description": "/Health/Mental Health/Depression"},
  {"id": 305, "description": "/Health/Nursing"},
  {"id": 306, "description": "/Health/Nursing/Assisted Living & Long Term Care"},
  {"id": 307, "description": "/Health/Nutrition"},
  {"id": 308, "description": "/Health/Nutrition/Special & Restricted Diets"},
  {"id": 309, "description": "/Health/Nutrition/Vitamins & Supplements"},
  {"id": 310, "description": "/Health/Oral & Dental Care"},
  {"id": 311, "description": "/Health/Pharmacy"},
  {"id": 312, "description": "/Health/Pharmacy/Drugs & Medications"},
  {"id": 313, "description": "/Health/Public Health"},
  {"id": 314, "description": "/Health/Public Health/Occupational Health & Safety"},
  {"id": 315, "description": "/Health/Reproductive Health"},
  {"id": 316, "description": "/Health/Substance Abuse"},
  {"id": 317, "description": "/Health/Substance Abuse/Drug & Alcohol Testing"},
  {"id": 318, "description": "/Health/Substance Abuse/Drug & Alcohol Treatment"},
  {"id": 319, "description": "/Health/Substance Abuse/Smoking & Smoking Cessation"},
  {"id": 320, "description": "/Health/Substance Abuse/Steroids & Performance-Enhancing Drugs"},
  {"id": 321, "description": "/Health/Vision Care"},
  {"id": 322, "description": "/Health/Vision Care/Eyeglasses & Contacts"},
  {"id": 323, "description": "/Health/Women's Health"},
  {"id": 324, "description": "/Hobbies & Leisure"},
  {"id": 325, "description": "/Hobbies & Leisure/Clubs & Organizations"},
  {"id": 326, "description": "/Hobbies & Leisure/Clubs & Organizations/Youth Organizations & Resources"},
  {"id": 327, "description": "/Hobbies & Leisure/Crafts"},
  {"id": 328, "description": "/Hobbies & Leisure/Crafts/Fiber & Textile Arts"},
  {"id": 329, "description": "/Hobbies & Leisure/Merit Prizes & Contests"},
  {"id": 330, "description": "/Hobbies & Leisure/Outdoors"},
  {"id": 331, "description": "/Hobbies & Leisure/Outdoors/Fishing"},
  {"id": 332, "description": "/Hobbies & Leisure/Outdoors/Hiking & Camping"},
  {"id": 333, "description": "/Hobbies & Leisure/Paintball"},
  {"id": 334, "description": "/Hobbies & Leisure/Radio Control & Modeling"},
  {"id": 335, "description": "/Hobbies & Leisure/Radio Control & Modeling/Model Trains & Railroads"},
  {"id": 336, "description": "/Hobbies & Leisure/Special Occasions"},
  {"id": 337, "description": "/Hobbies & Leisure/Special Occasions/Holidays & Seasonal Events"},
  {"id": 338, "description": "/Hobbies & Leisure/Special Occasions/Weddings"},
  {"id": 339, "description": "/Hobbies & Leisure/Water Activities"},
  {"id": 340, "description": "/Hobbies & Leisure/Water Activities/Boating"},
  {"id": 341, "description": "/Hobbies & Leisure/Water Activities/Surf & Swim"},
  {"id": 342, "description": "/Home & Garden"},
  {"id": 343, "description": "/Home & Garden/Bed & Bath"},
  {"id": 344, "description": "/Home & Garden/Bed & Bath/Bathroom"},
  {"id": 345, "description": "/Home & Garden/Domestic Services"},
  {"id": 346, "description": "/Home & Garden/Domestic Services/Cleaning Services"},
  {"id": 347, "description": "/Home & Garden/Gardening & Landscaping"},
  {"id": 348, "description": "/Home & Garden/Home & Interior Decor"},
  {"id": 349, "description": "/Home & Garden/Home Appliances"},
  {"id": 350, "description": "/Home & Garden/Home Furnishings"},
  {"id": 351, "description": "/Home & Garden/Home Furnishings/Curtains & Window Treatments"},
  {"id": 352, "description": "/Home & Garden/Home Furnishings/Kitchen & Dining Furniture"},
  {"id": 353, "description": "/Home & Garden/Home Furnishings/Lamps & Lighting"},
  {"id": 354, "description": "/Home & Garden/Home Furnishings/Living Room Furniture"},
  {"id": 355, "description": "/Home & Garden/Home Furnishings/Rugs & Carpets"},
  {"id": 356, "description": "/Home & Garden/Home Improvement"},
  {"id": 357, "description": "/Home & Garden/Home Improvement/Construction & Power Tools"},
  {"id": 358, "description": "/Home & Garden/Home Improvement/Doors & Windows"},
  {"id": 359, "description": "/Home & Garden/Home Improvement/Flooring"},
  {"id": 360, "description": "/Home & Garden/Home Improvement/House Painting & Finishing"},
  {"id": 361, "description": "/Home & Garden/Home Improvement/Plumbing"},
  {"id": 362, "description": "/Home & Garden/Home Safety & Security"},
  {"id": 363, "description": "/Home & Garden/Home Storage & Shelving"},
  {"id": 364, "description": "/Home & Garden/Home Swimming Pools, Saunas & Spas"},
  {"id": 365, "description": "/Home & Garden/HVAC & Climate Control"},
  {"id": 366, "description": "/Home & Garden/HVAC & Climate Control/Fireplaces & Stoves"},
  {"id": 367, "description": "/Home & Garden/Kitchen & Dining"},
  {"id": 368, "description": "/Home & Garden/Kitchen & Dining/Cookware & Diningware"},
  {"id": 369, "description": "/Home & Garden/Kitchen & Dining/Major Kitchen Appliances"},
  {"id": 370, "description": "/Home & Garden/Kitchen & Dining/Small Kitchen Appliances"},
  {"id": 371, "description": "/Home & Garden/Laundry"},
  {"id": 372, "description": "/Home & Garden/Laundry/Washers & Dryers"},
  {"id": 373, "description": "/Home & Garden/Nursery & Playroom"},
  {"id": 374, "description": "/Home & Garden/Pest Control"},
  {"id": 375, "description": "/Home & Garden/Yard & Patio"},
  {"id": 376, "description": "/Home & Garden/Yard & Patio/Lawn Mowers"},
  {"id": 377, "description": "/Internet & Telecom"},
  {"id": 378, "description": "/Internet & Telecom/Communications Equipment"},
  {"id": 379, "description": "/Internet & Telecom/Communications Equipment/Radio Equipment"},
  {"id": 380, "description": "/Internet & Telecom/Email & Messaging"},
  {"id": 381, "description": "/Internet & Telecom/Email & Messaging/Text & Instant Messaging"},
  {"id": 382, "description": "/Internet & Telecom/Email & Messaging/Voice & Video Chat"},
  {"id": 383, "description": "/Internet & Telecom/Mobile & Wireless"},
  {"id": 384, "description": "/Internet & Telecom/Mobile & Wireless/Mobile & Wireless Accessories"},
  {"id": 385, "description": "/Internet & Telecom/Mobile & Wireless/Mobile Apps & Add-Ons"},
  {"id": 386, "description": "/Internet & Telecom/Mobile & Wireless/Mobile Phones"},
  {"id": 387, "description": "/Internet & Telecom/Service Providers"},
  {"id": 388, "description": "/Internet & Telecom/Service Providers/Cable & Satellite Providers"},
  {"id": 389, "description": "/Internet & Telecom/Web Services"},
  {"id": 390, "description": "/Internet & Telecom/Web Services/Domain Parking"},
  {"id": 391, "description": "/Internet & Telecom/Web Services/Affiliate Programs"},
  {"id": 392, "description": "/Internet & Telecom/Web Services/Web Design & Development"},
  {"id": 393, "description": "/Jobs & Education"},
  {"id": 394, "description": "/Jobs & Education/Education"},
  {"id": 395, "description": "/Jobs & Education/Education/Colleges & Universities"},
  {"id": 396, "description": "/Jobs & Education/Education/Distance Learning"},
  {"id": 397, "description": "/Jobs & Education/Education/Homeschooling"},
  {"id": 398, "description": "/Jobs & Education/Education/Primary & Secondary Schooling (K-12)"},
  {"id": 399, "description": "/Jobs & Education/Education/Standardized & Admissions Tests"},
  {"id": 400, "description": "/Jobs & Education/Education/Teaching & Classroom Resources"},
  {"id": 401, "description": "/Jobs & Education/Education/Training & Certification"},
  {"id": 402, "description": "/Jobs & Education/Education/Vocational & Continuing Education"},
  {"id": 403, "description": "/Jobs & Education/Jobs"},
  {"id": 404, "description": "/Jobs & Education/Jobs/Career Resources & Planning"},
  {"id": 405, "description": "/Jobs & Education/Jobs/Job Listings"},
  {"id": 406, "description": "/Jobs & Education/Jobs/Resumes & Portfolios"},
  {"id": 407, "description": "/Law & Government"},
  {"id": 408, "description": "/Law & Government/Government"},
  {"id": 409, "description": "/Law & Government/Government/Courts & Judiciary"},
  {"id": 410, "description": "/Law & Government/Government/Visa & Immigration"},
  {"id": 411, "description": "/Law & Government/Legal"},
  {"id": 412, "description": "/Law & Government/Legal/Bankruptcy"},
  {"id": 413, "description": "/Law & Government/Legal/Legal Education"},
  {"id": 414, "description": "/Law & Government/Legal/Legal Services"},
  {"id": 415, "description": "/Law & Government/Military"},
  {"id": 416, "description": "/Law & Government/Public Safety"},
  {"id": 417, "description": "/Law & Government/Public Safety/Crime & Justice"},
  {"id": 418, "description": "/Law & Government/Public Safety/Emergency Services"},
  {"id": 419, "description": "/Law & Government/Public Safety/Law Enforcement"},
  {"id": 420, "description": "/Law & Government/Public Safety/Security Products & Services"},
  {"id": 421, "description": "/Law & Government/Social Services"},
  {"id": 422, "description": "/News"},
  {"id": 423, "description": "/News/Business News"},
  {"id": 424, "description": "/News/Business News/Company News"},
  {"id": 425, "description": "/News/Business News/Financial Markets News"},
  {"id": 426, "description": "/News/Gossip & Tabloid News/Scandals & Investigations"},
  {"id": 427, "description": "/News/Health News"},
  {"id": 428, "description": "/News/Politics"},
  {"id": 429, "description": "/News/Sports News"},
  {"id": 430, "description": "/News/Weather"},
  {"id": 431, "description": "/Online Communities"},
  {"id": 432, "description": "/Online Communities/Blogging Resources & Services"},
  {"id": 433, "description": "/Online Communities/Dating & Personals"},
  {"id": 434, "description": "/Online Communities/Dating & Personals/Matrimonial Services"},
  {"id": 435, "description": "/Online Communities/Dating & Personals/Personals"},
  {"id": 436, "description": "/Online Communities/Dating & Personals/Photo Rating Sites"},
  {"id": 437, "description": "/Online Communities/File Sharing & Hosting"},
  {"id": 438, "description": "/Online Communities/Online Goodies"},
  {"id": 439, "description": "/Online Communities/Online Goodies/Clip Art & Animated GIFs"},
  {"id": 440, "description": "/Online Communities/Online Goodies/Skins, Themes & Wallpapers"},
  {"id": 441, "description": "/Online Communities/Online Goodies/Social Network Apps & Add-Ons"},
  {"id": 442, "description": "/Online Communities/Photo & Video Sharing"},
  {"id": 443, "description": "/Online Communities/Photo & Video Sharing/Photo & Image Sharing"},
  {"id": 444, "description": "/Online Communities/Social Networks"},
  {"id": 445, "description": "/Online Communities/Virtual Worlds"},
  {"id": 446, "description": "/People & Society"},
  {"id": 447, "description": "/People & Society/Family & Relationships"},
  {"id": 448, "description": "/People & Society/Family & Relationships/Family"},
  {"id": 449, "description": "/People & Society/Family & Relationships/Marriage"},
  {"id": 450, "description": "/People & Society/Family & Relationships/Troubled Relationships"},
  {"id": 451, "description": "/People & Society/Kids & Teens"},
  {"id": 452, "description": "/People & Society/Kids & Teens/Children's Interests"},
  {"id": 453, "description": "/People & Society/Kids & Teens/Teen Interests"},
  {"id": 454, "description": "/People & Society/Religion & Belief"},
  {"id": 455, "description": "/People & Society/Seniors & Retirement"},
  {"id": 456, "description": "/People & Society/Social Issues & Advocacy"},
  {"id": 457, "description": "/People & Society/Social Issues & Advocacy/Charity & Philanthropy"},
  {"id": 458, "description": "/People & Society/Social Issues & Advocacy/Discrimination & Identity Relations"},
  {"id": 459, "description": "/People & Society/Social Issues & Advocacy/Green Living & Environmental Issues"},
  {"id": 460, "description": "/People & Society/Social Issues & Advocacy/Human Rights & Liberties"},
  {"id": 461, "description": "/People & Society/Social Issues & Advocacy/Poverty & Hunger"},
  {"id": 462, "description": "/People & Society/Social Issues & Advocacy/Work & Labor Issues"},
  {"id": 463, "description": "/People & Society/Social Sciences"},
  {"id": 464, "description": "/People & Society/Social Sciences/Economics"},
  {"id": 465, "description": "/People & Society/Social Sciences/Political Science"},
  {"id": 466, "description": "/People & Society/Social Sciences/Psychology"},
  {"id": 467, "description": "/People & Society/Subcultures & Niche Interests"},
  {"id": 468, "description": "/Pets & Animals"},
  {"id": 469, "description": "/Pets & Animals/Animal Products & Services/Pet Food & Supplies"},
  {"id": 470, "description": "/Pets & Animals/Animal Products & Services/Veterinarians"},
  {"id": 471, "description": "/Pets & Animals/Pets"},
  {"id": 472, "description": "/Pets & Animals/Pets/Birds"},
  {"id": 473, "description": "/Pets & Animals/Pets/Cats"},
  {"id": 474, "description": "/Pets & Animals/Pets/Dogs"},
  {"id": 475, "description": "/Pets & Animals/Pets/Exotic Pets"},
  {"id": 476, "description": "/Pets & Animals/Pets/Fish & Aquaria"},
  {"id": 477, "description": "/Pets & Animals/Pets/Horses"},
  {"id": 478, "description": "/Pets & Animals/Pets/Rabbits & Rodents"},
  {"id": 479, "description": "/Pets & Animals/Pets/Reptiles & Amphibians"},
  {"id": 480, "description": "/Pets & Animals/Wildlife"},
  {"id": 481, "description": "/Real Estate"},
  {"id": 482, "description": "/Real Estate/Real Estate Listings"},
  {"id": 483, "description": "/Real Estate/Real Estate Listings/Bank-Owned & Foreclosed Properties"},
  {"id": 484, "description": "/Real Estate/Real Estate Listings/Commercial Properties"},
  {"id": 485, "description": "/Real Estate/Real Estate Listings/Lots & Land"},
  {"id": 486, "description": "/Real Estate/Real Estate Listings/Residential Rentals"},
  {"id": 487, "description": "/Real Estate/Real Estate Listings/Residential Sales"},
  {"id": 488, "description": "/Real Estate/Real Estate Listings/Timeshares & Vacation Properties"},
  {"id": 489, "description": "/Real Estate/Real Estate Services"},
  {"id": 490, "description": "/Reference"},
  {"id": 491, "description": "/Reference/Directories & Listings"},
  {"id": 492, "description": "/Reference/Directories & Listings/Business & Personal Listings"},
  {"id": 493, "description": "/Reference/General Reference"},
  {"id": 494, "description": "/Reference/General Reference/Biographies & Quotations"},
  {"id": 495, "description": "/Reference/General Reference/Calculators & Reference Tools"},
  {"id": 496, "description": "/Reference/General Reference/Dictionaries & Encyclopedias"},
  {"id": 497, "description": "/Reference/General Reference/Forms Guides & Templates"},
  {"id": 498, "description": "/Reference/General Reference/Public Records"},
  {"id": 499, "description": "/Reference/General Reference/Time & Calendars"},
  {"id": 500, "description": "/Reference/Geographic Reference"},
  {"id": 501, "description": "/Reference/Geographic Reference/Maps"},
  {"id": 502, "description": "/Reference/Humanities"},
  {"id": 503, "description": "/Reference/Humanities/History"},
  {"id": 504, "description": "/Reference/Humanities/Myth & Folklore"},
  {"id": 505, "description": "/Reference/Humanities/Philosophy"},
  {"id": 506, "description": "/Reference/Language Resources"},
  {"id": 507, "description": "/Reference/Language Resources/Foreign Language Resources"},
  {"id": 508, "description": "/Reference/Libraries & Museums"},
  {"id": 509, "description": "/Reference/Libraries & Museums/Museums"},
  {"id": 510, "description": "/Science"},
  {"id": 511, "description": "/Science/Astronomy"},
  {"id": 512, "description": "/Science/Biological Sciences"},
  {"id": 513, "description": "/Science/Biological Sciences/Neuroscience"},
  {"id": 514, "description": "/Science/Chemistry"},
  {"id": 515, "description": "/Science/Computer Science"},
  {"id": 516, "description": "/Science/Earth Sciences"},
  {"id": 517, "description": "/Science/Earth Sciences/Atmospheric Science"},
  {"id": 518, "description": "/Science/Earth Sciences/Geology"},
  {"id": 519, "description": "/Science/Ecology & Environment"},
  {"id": 520, "description": "/Science/Ecology & Environment/Climate Change & Global Warming"},
  {"id": 521, "description": "/Science/Engineering & Technology"},
  {"id": 522, "description": "/Science/Engineering & Technology/Robotics"},
  {"id": 523, "description": "/Science/Mathematics"},
  {"id": 524, "description": "/Science/Mathematics/Statistics"},
  {"id": 525, "description": "/Science/Physics"},
  {"id": 526, "description": "/Science/Scientific Institutions"},
  {"id": 527, "description": "/Sensitive Subjects"},
  {"id": 528, "description": "/Shopping"},
  {"id": 529, "description": "/Shopping/Antiques & Collectibles"},
  {"id": 530, "description": "/Shopping/Apparel"},
  {"id": 531, "description": "/Shopping/Apparel/Athletic Apparel"},
  {"id": 532, "description": "/Shopping/Apparel/Casual Apparel"},
  {"id": 533, "description": "/Shopping/Apparel/Children's Clothing"},
  {"id": 534, "description": "/Shopping/Apparel/Clothing Accessories"},
  {"id": 535, "description": "/Shopping/Apparel/Costumes"},
  {"id": 536, "description": "/Shopping/Apparel/Eyewear"},
  {"id": 537, "description": "/Shopping/Apparel/Footwear"},
  {"id": 538, "description": "/Shopping/Apparel/Formal Wear"},
  {"id": 539, "description": "/Shopping/Apparel/Headwear"},
  {"id": 540, "description": "/Shopping/Apparel/Men's Clothing"},
  {"id": 541, "description": "/Shopping/Apparel/Swimwear"},
  {"id": 542, "description": "/Shopping/Apparel/Undergarments"},
  {"id": 543, "description": "/Shopping/Apparel/Women's Clothing"},
  {"id": 544, "description": "/Shopping/Auctions"},
  {"id": 545, "description": "/Shopping/Classifieds"},
  {"id": 546, "description": "/Shopping/Consumer Resources"},
  {"id": 547, "description": "/Shopping/Consumer Resources/Consumer Advocacy & Protection"},
  {"id": 548, "description": "/Shopping/Consumer Resources/Coupons & Discount Offers"},
  {"id": 549, "description": "/Shopping/Consumer Resources/Product Reviews & Price Comparisons"},
  {"id": 550, "description": "/Shopping/Entertainment Media"},
  {"id": 551, "description": "/Shopping/Entertainment Media/Entertainment Media Rentals"},
  {"id": 552, "description": "/Shopping/Gifts & Special Event Items"},
  {"id": 553, "description": "/Shopping/Gifts & Special Event Items/Cards & Greetings"},
  {"id": 554, "description": "/Shopping/Gifts & Special Event Items/Flowers"},
  {"id": 555, "description": "/Shopping/Gifts & Special Event Items/Gifts"},
  {"id": 556, "description": "/Shopping/Luxury Goods"},
  {"id": 557, "description": "/Shopping/Mass Merchants & Department Stores"},
  {"id": 558, "description": "/Shopping/Photo & Video Services"},
  {"id": 559, "description": "/Shopping/Tobacco Products"},
  {"id": 560, "description": "/Shopping/Toys"},
  {"id": 561, "description": "/Shopping/Toys/Building Toys"},
  {"id": 562, "description": "/Shopping/Toys/Die-cast & Toy Vehicles"},
  {"id": 563, "description": "/Shopping/Toys/Dolls & Accessories"},
  {"id": 564, "description": "/Shopping/Toys/Ride-On Toys & Wagons"},
  {"id": 565, "description": "/Shopping/Toys/Stuffed Toys"},
  {"id": 566, "description": "/Sports"},
  {"id": 567, "description": "/Sports/Animal Sports"},
  {"id": 568, "description": "/Sports/College Sports"},
  {"id": 569, "description": "/Sports/Combat Sports"},
  {"id": 570, "description": "/Sports/Combat Sports/Boxing"},
  {"id": 571, "description": "/Sports/Combat Sports/Martial Arts"},
  {"id": 572, "description": "/Sports/Combat Sports/Wrestling"},
  {"id": 573, "description": "/Sports/Extreme Sports"},
  {"id": 574, "description": "/Sports/Extreme Sports/Drag & Street Racing"},
  {"id": 575, "description": "/Sports/Fantasy Sports"},
  {"id": 576, "description": "/Sports/Individual Sports"},
  {"id": 577, "description": "/Sports/Individual Sports/Cycling"},
  {"id": 578, "description": "/Sports/Individual Sports/Golf"},
  {"id": 579, "description": "/Sports/Individual Sports/Gymnastics"},
  {"id": 580, "description": "/Sports/Individual Sports/Racquet Sports"},
  {"id": 581, "description": "/Sports/Individual Sports/Skate Sports"},
  {"id": 582, "description": "/Sports/Individual Sports/Track & Field"},
  {"id": 583, "description": "/Sports/International Sports Competitions"},
  {"id": 584, "description": "/Sports/International Sports Competitions/Olympics"},
  {"id": 585, "description": "/Sports/Motor Sports"},
  {"id": 586, "description": "/Sports/Sporting Goods"},
  {"id": 587, "description": "/Sports/Sporting Goods/Sports Memorabilia"},
  {"id": 588, "description": "/Sports/Sporting Goods/Winter Sports Equipment"},
  {"id": 589, "description": "/Sports/Sports Coaching & Training"},
  {"id": 590, "description": "/Sports/Team Sports"},
  {"id": 591, "description": "/Sports/Team Sports/American Football"},
  {"id": 592, "description": "/Sports/Team Sports/Australian Football"},
  {"id": 593, "description": "/Sports/Team Sports/Baseball"},
  {"id": 594, "description": "/Sports/Team Sports/Basketball"},
  {"id": 595, "description": "/Sports/Team Sports/Cheerleading"},
  {"id": 596, "description": "/Sports/Team Sports/Cricket"},
  {"id": 597, "description": "/Sports/Team Sports/Hockey"},
  {"id": 598, "description": "/Sports/Team Sports/Rugby"},
  {"id": 599, "description": "/Sports/Team Sports/Soccer"},
  {"id": 600, "description": "/Sports/Team Sports/Volleyball"},
  {"id": 601, "description": "/Sports/Water Sports"},
  {"id": 602, "description": "/Sports/Water Sports/Surfing"},
  {"id": 603, "description": "/Sports/Water Sports/Swimming"},
  {"id": 604, "description": "/Sports/Winter Sports"},
  {"id": 605, "description": "/Sports/Winter Sports/Ice Skating"},
  {"id": 606, "description": "/Sports/Winter Sports/Skiing & Snowboarding"},
  {"id": 607, "description": "/Travel"},
  {"id": 608, "description": "/Travel/Air Travel"},
  {"id": 609, "description": "/Travel/Air Travel/Airport Parking & Transportation"},
  {"id": 610, "description": "/Travel/Bus & Rail"},
  {"id": 611, "description": "/Travel/Car Rental & Taxi Services"},
  {"id": 612, "description": "/Travel/Cruises & Charters"},
  {"id": 613, "description": "/Travel/Hotels & Accommodations"},
  {"id": 614, "description": "/Travel/Hotels & Accommodations/Vacation Rentals & Short-Term Stays"},
  {"id": 615, "description": "/Travel/Specialty Travel"},
  {"id": 616, "description": "/Travel/Tourist Destinations"},
  {"id": 617, "description": "/Travel/Tourist Destinations/Beaches & Islands"},
  {"id": 618, "description": "/Travel/Tourist Destinations/Mountain & Ski Resorts"},
  {"id": 619, "description": "/Travel/Tourist Destinations/Regional Parks & Gardens"},
  {"id": 620, "description": "/Travel/Tourist Destinations/Theme Parks"},
  {"id": 621, "description": "/Travel/Tourist Destinations/Zoos-Aquariums-Preserves"},
  {"id": 622, "description": "/Unknown"}
]
