export const EDUCATION_HOSTS = {
    'class.com': 0,
    'blackboard.com': 0,
    'khanacademy.org': 0,
    'ixl.com': 0,
    'lexiapowerup.com': 0,
    'dns.google': 0,
    'mail.google.com': 0,
    'gmail.com': 0,
    'schoology.com': 0,
    'acceleratelearning.com': 0,
    'app.acceleratelearning.com': 0,
    'kahoot.it': 0,
    'nwea.org': 0,
    'test.mapnwea.org': 0,
    'drcdirect.com': 0,
    'laslinks.com': 0,
    'noredink.com': 0,
    'newsela.com': 0,
    'gimkit.com': 0,
    'blooket.com': 0,
    'yup.com': 0,
    'docs.google.com': 0,
    'stemscopes.com': 0,
};
