name: Dependabot Merged Release

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'}} # Detect that the PR author is dependabot
    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL" # Use Github CLI to merge automatically the PR
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GIT_MERGE_TOKEN }}
  build:
    runs-on: ubuntu-latest
    needs: auto-merge
    steps:
      - name: Checkout github repo (+ download lfs dependencies)
        uses: actions/checkout@v4
        with:
          lfs: true
          persist-credentials: false
          fetch-depth: 0

      - name: Init git user
        run: |
          git config --local user.email "abbas@safekids.ai"
          git config --local user.name "Release Workflow"

      - name: Checkout LFS objects
        run: git lfs pull

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: latest
          run_install: false

      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
          scope: '@safekids-ai'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build and Release
        run: |
          npx nx build:prod
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
